added signing to atx publisher and received
spacemeshos/go-spacemesh pull request #1404
Opened 2019-09-08 15:07 UTC by antonlerner

2019-09-22 08:57 UTC, zalmen requested changes

2019-09-22 08:57 UTC, zalmen commented on common/types/activation.go
> +	*ActivationTx
continuing our talk f2f, why not keep the actual atx as a byte array and avoid the double marshaling?

2019-09-22 08:57 UTC, zalmen commented on miner/block_builder.go
> +	err = types.ValidateSignedAtx(signedAtx)
what about validating the ATXs that we got via sync flows?

2019-09-22 08:57 UTC, zalmen commented on activation/atxdb.go
> +	err = db.ValidateSignedAtx(*pub, atx)
Why aren't you skipping this validation if there is an empty prev atx? I know that `ValidateSignedAtx` will return nil, but it makes this code not straight forward for the reader of the code which might assume that you're validating the sig also in the first atx

2019-09-22 08:57 UTC, zalmen commented on activation/atxdb.go
> +		id := signing.NewPublicKey(util.Hex2Bytes(atx.NodeId.Key))
you need to use `pub` and not the ID from `NodeId`, otherwise there is no sig validation for first ATXs

2019-09-22 08:57 UTC, zalmen commented on activation/atxdb.go
> +	pub, err := types.ExtractPublicKey(atx)
You need somewhere to validate that `pub` and the id in `NodeId` match

2019-09-22 08:57 UTC, zalmen commented on activation/atxdb.go
> +		return errInvalidSig
you should return the err that was received from `GetIdentity` (return it as-is or embedded in a new error)

2019-09-22 08:57 UTC, zalmen commented on nipst/nipst.go
> +			//Identity:     []byte(nil),
remove

2019-09-22 14:42 UTC, antonlerner commented on miner/block_builder.go
> +	err = types.ValidateSignedAtx(signedAtx)
They use `SyntacticallyValidateAtx` as the validation function for received atxs

2019-09-22 14:43 UTC, antonlerner commented on common/types/activation.go
> +	*ActivationTx
I was under the impression that we didn't want to do any optimisations at this stage

2019-09-23 07:28 UTC, zalmen commented on common/types/activation.go
> +	*ActivationTx
Actually it was an old comment of mine, we can talk about it f2f

2019-10-03 12:43 UTC, zalmen approved these changes

2019-10-03 13:44 UTC, merged