handle partial responses
spacemeshos/go-spacemesh pull request #1410
Opened 2019-09-10 15:16 UTC by almogdepaz

send batch block requests

2019-09-10 15:20 UTC, almogdepaz commented on sync/validation_queue.go
>  	}
this is a revert of #1409

2019-09-11 12:27 UTC, zalmen requested changes

2019-09-11 12:27 UTC, zalmen commented on sync/validation_queue.go
> +			vq.Error(fmt.Sprintf("could not retrieve a block in view "))
print the block id

2019-09-11 12:27 UTC, zalmen commented on sync/validation_queue.go
> +		vq.visited[id] = struct{}{}
check if you really need `visited`

2019-09-11 12:27 UTC, zalmen commented on sync/validation_queue.go
> +			return
Don't you mean `continue`?

2019-09-11 12:29 UTC, almogdepaz commented on sync/validation_queue.go
> +			return
why, yes i do!

2019-09-11 12:29 UTC, almogdepaz commented on sync/validation_queue.go
> +		vq.visited[id] = struct{}{}
removed

2019-09-11 14:59 UTC, barakshani approved these changes

2019-09-12 09:57 UTC, merged

2019-09-12 10:01 UTC, almogdepaz commented
resolves   #1401