Only apply rewards on layers < pbase
spacemeshos/go-spacemesh pull request #1445
Opened 2019-10-23 13:05 UTC by noamnelke

TODO:
- [ ] Add tests

2019-10-26 18:53 UTC, barakshani commented on mesh/mesh.go
> +	for layerId := oldPbase; layerId < newPbase; layerId++ {
The for loop should stop at Min(newPbase + m.config.RewardMaturity, lyr.Index()), otherwise we may be postponing the reward allocation.
With the current code I'm afraid that simply changing it will cause double allocations.

2019-10-26 18:53 UTC, barakshani commented on mesh/mesh.go
> +		}
If I made the calculations correctly, then in the following example demonstrates that we may skip some layers from giving rewards, with or without applying my comment to line 149.

Suppose RewardMaturity=3, and p_base is stuck on 10 until layer 20. Consider the case where:
layer 20: old_pbase = 10, new_pbase = 16.
layer 21: old = 16, new = 20.
layer 22: old = 20, new = 21.
**
We should try to be more systematic in convincing ourselves that we allocate rewards correctly. For the moment I support having a variable that stores the last reward-allocated layer.

2019-10-28 10:03 UTC, barakshani approved these changes

2019-11-03 15:23 UTC, zalmen requested changes

2019-11-03 15:23 UTC, zalmen commented on mesh/mesh.go
> +		valid, err := m.ContextualValidity(bl.ID())
What happens if `bl.ID()` isn't valid? per @almogdepaz the db will return an error when queried on an unknown key

2019-11-04 07:21 UTC, zalmen approved these changes

2019-11-04 07:33 UTC, merged