Added tx generator and modified test_bs tests
spacemeshos/go-spacemesh pull request #1685
Opened 2020-01-13 14:20 UTC by AmitShaul

## Motivation
Create a tool who sends transactions to serve us with our testing/stress testing.

## Changes
modified the tests that resides in test_bs

2020-01-14 12:17 UTC, noamnelke reviewed
The previous `test_transactions` did the following:
- Send from the tap to 10 random (new) accounts a random amount
- Ensure that everyone's balance and nonce got updated
- Send 10 txs from those 10 accounts randomly (sometimes multiple txs from same account) to 10 more accounts. Amount is random.
- Ensure that everyone's balance and nonce got updated
- Send 10 txs from the total list of 20 accounts
- Ensure that everyone's balance and nonce got updated
- Missing: sending to an existing account

The new `test_transactions` does the following:
- Sends 50 coins from the tap to 2 new accounts
- Ensure that everyone's balance and nonce got updated
- From each of those 2, send 10 transactions, either to themselves or to the other guy, 1 coin per tx
- Ensure that everyone's balance and nonce got updated

I'm thinking that it's probably fine, as using random amounts and another hop doesn't really test much, and sending coins to the same account and to other existing accounts is a great addition. The only thing I'm wondering about is if this was an intentional change. If it was - next time it would be great to discuss it ahead of the PR, or even ahead of coding it. If it wasn't intentional - there's also something to learn from here.

2020-01-14 12:17 UTC, noamnelke commented on Dockerfile
> +# Force the go compiler to use models
it looks like you did a find & replace from `modules` to `models`... Not sure why, but here it's definitely wrong, it should be `modules`.

2020-01-14 12:17 UTC, noamnelke commented on log/log.go
> +// to spacemesh models such as app and identity.
undo

2020-01-14 12:17 UTC, noamnelke commented on setup_env.sh
> +# Current version of grpc_gateway does not support go models, so we install it to the gopath
undo

2020-01-14 12:17 UTC, noamnelke commented on sync/syncer.go
> +//api for other models to check if they should listen to gossip
undo

2020-01-14 12:17 UTC, noamnelke commented on tests/convenience.py
> +        time.sleep(1)
this is nice for local, but I wonder if the `\r` trick will work in Travis (my guess is that it will look messed up). Maybe detect if this is an interactive terminal and if it isn't then just print a line every few seconds instead (or nothing at all). I'm doing something similar with the colors - ask me if you need guidance.

2020-01-14 12:17 UTC, noamnelke commented on tests/convenience.py
> +        time.sleep(1)
Just realized you've removed my beautiful output formatting 😢 
Not that important I guess, but it did make following the log easier, as it highlighted the important parts.

2020-01-14 12:17 UTC, noamnelke commented on tests/test_bs.py
> +from tests.tx_generator.models.tx_generator import TxGenerator
unused import

2020-01-14 12:17 UTC, noamnelke commented on tests/test_bs.py
>  from tests.ed25519.eddsa import genkeypair
no longer used

2020-01-14 12:17 UTC, noamnelke commented on tests/test_bs.py
>  from tests.ed25519.eddsa import genkeypair
There's actually a bunch of no longer used imports that should be cleaned up:

```python
import copy
from enum import Enum
import json
import pprint
import random
import sys
from typing import List
```

2020-01-19 11:01 UTC, AmitShaul commented on Dockerfile
> +# Force the go compiler to use models
fixed

2020-01-19 11:01 UTC, AmitShaul commented on log/log.go
> +// to spacemesh models such as app and identity.
fixed

2020-01-19 11:02 UTC, AmitShaul commented on setup_env.sh
> +# Current version of grpc_gateway does not support go models, so we install it to the gopath
fixed (don't know how it happened)

2020-01-19 11:02 UTC, AmitShaul commented on sync/syncer.go
> +//api for other models to check if they should listen to gossip
fixed

2020-01-19 11:05 UTC, AmitShaul commented on tests/convenience.py
> +        time.sleep(1)
I'll check about Travis, I've got a feeling it will be ok, if not then I will change it

2020-01-19 11:06 UTC, AmitShaul commented on tests/convenience.py
> +        time.sleep(1)
and about your output, it was beautiful it's true but the output is different now and readable just the same without the colors

2020-01-19 11:11 UTC, AmitShaul commented on tests/test_bs.py
> +from tests.tx_generator.models.tx_generator import TxGenerator
removed

2020-01-19 11:12 UTC, AmitShaul commented on tests/test_bs.py
>  from tests.ed25519.eddsa import genkeypair
removed all unused imports

2020-01-19 12:36 UTC, AmitShaul commented on tests/convenience.py
> +        time.sleep(1)
we're using the same end="\r" print in stateful.py and deployment.py

2020-01-19 15:24 UTC, AmitShaul commented on sync/syncer.go
> +//api for other models to check if they should listen to gossip
e7ee3d8b26da1ee777287a4bdaea1130c8804b89

2020-01-19 15:24 UTC, AmitShaul commented on setup_env.sh
> +# Current version of grpc_gateway does not support go models, so we install it to the gopath
e7ee3d8b26da1ee777287a4bdaea1130c8804b89

2020-01-20 07:35 UTC, noamnelke commented
bors try

2020-01-20 08:16 UTC, noamnelke requested changes

2020-01-20 08:16 UTC, noamnelke commented on tests/test_bs.py
> -current_index = 'kubernetes_cluster-' + today_date
It looks like making this variable non-global broke `hare`, `sync` and `late nodes` tests (see [results](https://travis-ci.org/spacemeshos/go-spacemesh/builds/639364172)). Either make it global again, or fix the other tests some other way.

2020-01-20 09:32 UTC, noamnelke approved these changes

2020-01-20 09:41 UTC, AmitShaul commented
bors merge

2020-01-20 10:40 UTC, closed without merging