Fix bug in StartPost
spacemeshos/go-spacemesh pull request #1714
Opened 2020-01-22 18:11 UTC by lrettig

case statement was missing fallthrough. Updates tests accordingly.

## Motivation
Spotted while working on #1700 (but probably unrelated).

## Changes
Fix case statement

## Test Plan
Updated tests accordingly.

2020-03-09 09:32 UTC, noamnelke requested changes
Good catch!

Sorry for not getting to this sooner (you can ping me on slack next time if I miss PRs).

2020-03-09 09:32 UTC, noamnelke commented on activation/activation.go
>  		default:
I think that it's better to remove the `default:` clause here, than add a `fallthrough`. There aren't any other values that `b.initStatus` can have that aren't explicitly covered by the `switch` (it won't get to the switch if it's `InitIdle`).

```suggestion
```

2020-03-10 08:24 UTC, noamnelke approved these changes

2020-03-10 08:39 UTC, avive commented
Can someone please check if this fix also fixed #1879 - there are line numbers in the go code in the stack trace for this panic in the screen shot. @lrettig @noamnelke - I got this panic few times on my smesher.

2020-03-10 09:03 UTC, noamnelke commented
I'm not 100% sure, but from quickly trying to follow the code (not all the way through) I think a `panic` is plausible.

However, in order for this to cause a `panic` a restart of the node during PoST initialization is required. Since you said you can reproduce it without a restart, at the very least there's another cause for that issue.

2020-03-10 11:56 UTC, lrettig commented
bors merge

2020-03-10 13:00 UTC, closed without merging