Refactor test_bs test file
spacemeshos/go-spacemesh pull request #1864
Opened 2020-02-26 12:54 UTC by AmitShaul

## Motivation
test_bs is a mess, all setup functions and basic fixtures are in it.
refactor this file to contain only mining tests

2020-02-26 12:54 UTC, AmitShaul commented
bors try

2020-02-26 12:57 UTC, AmitShaul commented
bors try

2020-02-26 12:58 UTC, AmitShaul commented
bors try

2020-02-26 13:16 UTC, AmitShaul commented
bors try

2020-02-27 10:05 UTC, AmitShaul commented
bors try

2020-02-27 12:21 UTC, AmitShaul commented
bors try

2020-03-01 15:02 UTC, noamnelke requested changes
LGTM, other than that one comment.

2020-03-01 15:02 UTC, noamnelke commented on tests/conftest.py
> +# The following fixture is currently not in used and mark for deprecation
Please remove this commend and preferably also the unused, deprecated method.

2020-03-01 15:04 UTC, noamnelke approved these changes

2020-03-01 15:06 UTC, AmitShaul commented on tests/conftest.py
> +# The following fixture is currently not in used and mark for deprecation
removed in aada8c1fbe2643506f7d34c0fa022093e17d9d2a

2020-03-01 15:07 UTC, AmitShaul commented
bors merge

2020-03-01 16:56 UTC, closed without merging