Improve issue templates
spacemeshos/go-spacemesh pull request #1883
Opened 2020-03-09 13:41 UTC by noamnelke

## Motivation
Make `go-spacemesh` issue templates more useful.

## Changes
Include links to https://github.com/spacemeshos/smips and discord (to direct users there and reduce "support issue" creation), make it clear what each template is for and remove boilerplate that existed in previous templates.

2020-03-10 12:11 UTC, avive requested changes

2020-03-10 12:11 UTC, avive commented on .github/ISSUE_TEMPLATE/bug-report.md
> +The log file is called `spacemeshlog.txt` and it is located in your documents folder. -->
- spacemesh-log.txt
- it is not in the docs folder, it is in the spacemesh data folder. See bottom of this page: https://testnet.spacemesh.io/#ffnet
- please add recommendation to upload screen shot - for example - an error dialog box or a badly displayed data. e..g wrong balance, Nan tx nonce, etc...

2020-03-10 12:11 UTC, avive commented on .github/ISSUE_TEMPLATE/bug-report.md
> + - App Version (if applicable): [e.g. 1.2.3]
Please add: The app version string is accessible from the app's settings.

2020-03-10 18:46 UTC, avive approved these changes

2020-03-11 08:47 UTC, noamnelke commented
bors merge

2020-03-11 09:29 UTC, noamnelke commented
bors merge

2020-03-11 10:34 UTC, closed without merging