Activation lint
spacemeshos/go-spacemesh pull request #1907
Opened 2020-03-18 13:11 UTC by antonlerner

## Motivation
Better linting of the Activation, Miner and State dirs

still needs more complex comments on private methods

I've also did not comment and lint :
state/processor.go
nipst related files
post related files

2020-03-18 13:39 UTC, noamnelke requested changes
I found a few typos (and one actual mistake), I suggest running the IDE's spell checker on these files.

2020-03-18 13:39 UTC, noamnelke commented on activation/activation.go
> +type poETNumberOfTickProvider struct {
this is very confusing... Let's consider poet a word and make the `ET` lowercase?

2020-03-18 13:39 UTC, noamnelke commented on activation/activation.go
> +// meshProviderMock
remove, since you made this private

2020-03-18 13:39 UTC, noamnelke commented on activation/activation.go
> +// it is responsible for
incomplete comment

2020-03-18 13:39 UTC, noamnelke commented on activation/activation.go
> +// SignAtx signs the atx atx and assigns the signature into atx.Sig
```suggestion
// SignAtx signs the atx and assigns the signature into atx.Sig
```

2020-03-18 13:39 UTC, noamnelke commented on activation/activation.go
> +// StartPost initiates post commitment generation process. it returns an error if a process is already on progress or
```suggestion
// StartPost initiates post commitment generation process. It returns an error if a process is already in progress or
```

2020-03-18 13:39 UTC, noamnelke commented on activation/activation_test.go
> +	atxDb            atxDBProvider
Should be `atxDB` (capital b), I guess?

2020-03-18 13:39 UTC, noamnelke commented on activation/atxdb.go
>  type ActivationDb struct {
`ActivationDB`?

2020-03-18 13:39 UTC, noamnelke commented on activation/atxdb.go
> +func NewActivationDb(dbstore database.Database, idstore idStore, meshDb *mesh.MeshDB, layersPerEpoch uint16, nipstValidator nipstValidator, log log.Log) *ActivationDb {
`NewActivationDB`?

2020-03-18 13:39 UTC, noamnelke commented on activation/cache.go
> +// ActivesetCache holds and lru cache of the active set size for a view hash.
```suggestion
// ActivesetCache holds an lru cache of the active set size for a view hash.
```

2020-03-18 13:39 UTC, noamnelke commented on activation/cache.go
> +// performed
```suggestion
// AtxCache holds an lru cache of ActivationTxHeader structs of recent atx used to calculate active set size
// ideally this cache will hold the atxs created in latest epoch, on which most of active set size calculation will be
// performed
```

2020-03-18 13:39 UTC, noamnelke commented on activation/cache.go
> +// Get gets the corresponding Atx header to the given id id, it also returns a boolean to indicate whether the item
```suggestion
// Get gets the corresponding Atx header to the given id, it also returns a boolean to indicate whether the item
```

2020-03-18 13:39 UTC, noamnelke commented on miner/block_builder.go
> +// AtxsPerBlockLimit indicates the maximum number of atxs a block can refrence
```suggestion
// AtxsPerBlockLimit indicates the maximum number of atxs a block can reference
```

2020-03-18 13:39 UTC, noamnelke commented on miner/block_builder.go
> +// blopck oracly chen it should create a block. this function returns an error if Start was already called once
```suggestion
// block oracle when it should create a block. This function returns an error if Start was already called once
```

2020-03-18 13:39 UTC, noamnelke commented on miner/block_builder.go
> +//used from external API call to dd transcrtion
```suggestion
// used from external API call to add transaction
```

2020-03-18 13:39 UTC, noamnelke commented on miner/tx_pool.go
> +// Get returns transaction by provided id id, it returns an error it transaction is not found
```suggestion
// Get returns transaction by provided id, it returns an error if transaction is not found
```

2020-03-18 13:39 UTC, noamnelke commented on miner/tx_pool.go
> +// GetTxIdsByAddress returns all transactions from a specific source address
```suggestion
// GetTxIdsByAddress returns all transactions from/to a specific address
```

2020-03-18 13:39 UTC, noamnelke commented on miner/tx_pool.go
> +// GetTxsForBlock gets a specific number of random txs for a block. this function also receives a state calculation function
```suggestion
// GetTxsForBlock gets a specific number of random txs for a block. This function also receives a state calculation function
```

2020-03-18 13:39 UTC, noamnelke commented on miner/tx_pool.go
> +// Put inserts a transaction into the mem pool. it indexes it by source and dest addresses as well
```suggestion
// Put inserts a transaction into the mem pool. It indexes it by source and dest addresses as well
```

2020-03-18 13:39 UTC, noamnelke commented on state/account_state.go
> +// AccountState is the interface defined to auery a single account state
```suggestion
// AccountState is the interface defined to query a single account state
```

2020-03-18 13:39 UTC, noamnelke commented on state/account_state.go
> +// StateObj is the struct in which account information is stored. it contains account info such as nonce and balane
```suggestion
// StateObj is the struct in which account information is stored. It contains account info such as nonce and balance
```

2020-03-18 13:39 UTC, noamnelke commented on state/dump.go
> +// DumpAccount is an helper struct that helps dumping account balance and nonce in json form
```suggestion
// DumpAccount is a helper struct that helps dumping account balance and nonce in json form
```

2020-03-18 13:39 UTC, noamnelke commented on state/dump.go
> +// Dump is a sstruct used to dump an entire state root into json form
```suggestion
// Dump is a struct used to dump an entire state root into json form
```

2020-03-18 13:39 UTC, noamnelke commented on state/global_state.go
> +// account data in its leaves. it also stores a dirty object list to dump when state is committed into db
```suggestion
// StateDB is the struct that performs logging of all account states. It consists of a state trie that contains all
// account data in its leaves. It also stores a dirty object list to dump when state is committed into db
```

2020-03-18 13:39 UTC, noamnelke commented on state/processor.go
> +// Projector interface defince the interface for a struct that can project the state aof an account by applying txs from
```suggestion
// Projector interface defines the interface for a struct that can project the state of an account by applying txs from
```

2020-03-22 11:17 UTC, noamnelke approved these changes
Looks good in general. There was one meaningless comment that should be fixed. Can be merged afterwards.

2020-03-22 11:17 UTC, noamnelke commented on cmd/node/app_test.go
> +func (suite *AppTestSuite) initMultipleInstances(cfg *config.Config, rolacle *eligibility.FixedRolacle, rng *amcl.RAND, numOfInstances int, storeFormat string, genesisTime string, poetClient *activat
Isn't this causing an override of the type by the variable? Maybe rename the var to `net`?

2020-03-22 11:17 UTC, noamnelke commented on cmd/node/multi_node.go
> +// StartNotifying is empty because this clokc is manual
```suggestion
// StartNotifying is empty because this clock is manual
```

2020-03-22 11:17 UTC, noamnelke commented on cmd/node/node.go
> +// Initialize is what he wants to execute Initialize app starts
Let's write something meaningful here

2020-03-22 12:15 UTC, antonlerner commented
bors merge

2020-03-22 14:49 UTC, antonlerner commented
bors merge

2020-03-22 15:52 UTC, closed without merging