added --ntp-servers cli option
spacemeshos/go-spacemesh pull request #2221
Opened 2020-12-03 19:13 UTC by narayanprusty

## Motivation

Currently we create a separate build during testnet release for Chinese smeshers as our default NTP servers are blocked in china. 

## Changes

Now smeshers can provide a list of NTP servers via `--ntp-servers` CLI option

## Test Plan

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed

2020-12-06 14:02 UTC, noamnelke reviewed
I'm wondering if using a separate file for this is the best strategy. I think we should be consistent with how we implement configuration.

We have a framework for this and we have a config file. I think this should be another value in the config, and not a separate file.

2020-12-07 10:08 UTC, narayanprusty commented
> I'm wondering if using a separate file for this is the best strategy. I think we should be consistent with how we implement configuration.
> 
> We have a framework for this and we have a config file. I think this should be another value in the config, and not a separate file.

2020-12-07 10:30 UTC, narayanprusty commented
@noamnelke I agree using the `--config` option would be the best practice. I have uploaded the PR to adhere to the framework we have currently.

2020-12-07 16:52 UTC, noamnelke approved these changes
:shipit:

2020-12-08 09:45 UTC, y0sher commented
just small comment I would also add it to the `config.toml` file

2020-12-08 15:06 UTC, noamnelke requested changes

2020-12-08 15:06 UTC, noamnelke commented on config.toml
> +ntp-servers = ["time1.cloud.tencent.com", "0.cn.pool.ntp.org"]
Note that this will override the default config. If we include it, we should put the entire list here.

2020-12-11 13:36 UTC, lrettig requested changes
@narayanprusty what happens if a user passes the `--ntp-servers` CLI flag but only specifies, say, a single NTP server? Does it replace the others? Do we want to enforce a minimum number? It would be good to make this clear in the CLI flag description

2020-12-20 08:06 UTC, narayanprusty commented
@lrettig Looks like the total NTP servers URLs should be greater than the number of NTP queries required to be done. I have expanded the CLI flag description accordingly.

2020-12-22 01:46 UTC, lrettig requested changes

2020-12-22 01:46 UTC, lrettig commented on cmd/root.go
> +		"ntp-servers", config.TIME.NTPServers, "Load NTP servers URLs. The total NTP server URLs should be greater than number of NTP queries")
I think this message could be a little clearer, how's this?

```suggestion
		"ntp-servers", config.TIME.NTPServers, "A list of NTP servers to query (e.g., 'time.google.com'). Overrides the list in config. Must contain more servers than the number of ntp-queries.")
```

2020-12-22 15:07 UTC, lrettig approved these changes
LGTM thanks!

2020-12-22 17:36 UTC, noamnelke approved these changes
:shipit:

2020-12-23 01:38 UTC, lrettig commented
Quick question: assuming that we intend this to replace #2142, how do we intend to package this up so that it still works in places like China that need a different set of NTP servers? Should Smapp detect location and set NTP servers accordingly? Or something else?

2020-12-24 06:57 UTC, noamnelke commented
@lrettig we can still package a separate SMApp, with a different config which would be the same user experience as today, but with a single `go-spacemesh` version (the purpose of this PR is to eliminate the extra version).

Eventually we want to both make the list configurable and make handling of failures smarter (so we can start with a large list of servers by default and eliminate ones that don’t work or have high latency).

Eventually-eventually we want to not rely on NTP at all and have some internal mechanism like bitcoin does.

2021-01-05 18:26 UTC, narayanprusty commented
bors merge

2021-01-06 08:36 UTC, noamnelke commented
bors merge

2021-01-06 09:38 UTC, closed without merging