Fix GHA Automated Builds
spacemeshos/go-spacemesh pull request #2259
Opened 2021-01-17 07:28 UTC by narayanprusty

Currently the release builds are failing because protoc requires $GOPATH/bin to be added to $PATH. This PR adds this path so that protoc binaries can be found during `make build`

**Note that for builds to work the version.txt file shouldn't have a new line character.**

2021-01-17 14:12 UTC, noamnelke approved these changes
Let's restore the end-of-file line break before merging?

2021-01-17 14:12 UTC, noamnelke commented on .github/workflows/release.yml
> +          prerelease: true
why remove the end-of-file line break?

2021-01-17 14:13 UTC, noamnelke requested changes
Actually... just noticed the comment... if you don't want a line break in `version.txt` - then let's fix it here.

2021-01-17 14:46 UTC, noamnelke approved these changes

2021-01-18 12:23 UTC, narayanprusty commented
bors merge

2021-01-18 21:38 UTC, lrettig commented
protoc is no longer used in production - it was removed a long time ago - it's only needed for the current build cycle because it's using very old code. Should this change be reverted?

2021-01-19 12:25 UTC, noamnelke commented
once the testnet is caught up with the new code we can consider it, but I think puting `$GOPATH/bin` in `$PATH` is standard practice, so it's not a big deal if it stays this way, isn't it?

2021-01-19 18:48 UTC, lrettig commented
> once the testnet is caught up with the new code we can consider it, but I think puting `$GOPATH/bin` in `$PATH` is standard practice, so it's not a big deal if it stays this way, isn't it?

True, it's probably no big deal, but the `ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'` caught my eye and I'm not 100% sure it's something we want in production forever - I guess that's up to @narayanprusty. This change _could_ be removed from `develop` and just cherry-picked into future testnet builds (until testnet catches up with the new API code).

2021-01-20 09:19 UTC, noamnelke commented
>This change _could_ be removed from `develop` and just cherry-picked into future testnet builds (until testnet catches up with the new API code).

Yes, I agree.

@narayanprusty WDYT?

2021-01-20 16:13 UTC, narayanprusty commented
Having $GOPATH/bin in $PATH is already deprecated. https://blog.golang.org/modules2019 As we have protoc in old code therefore we needed it. 

`ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'` doesn't cause any security issues as it's defined for a specific step and not at global level. 

Regardless of that, I can create another PR to revert it and re-open this PR so that we can cherry-pick this PR until we have old code.

2021-01-20 16:19 UTC, narayanprusty commented
@noamnelke @lrettig Here is the PR to revert the code: #2265

2021-01-21 08:35 UTC, noamnelke commented
No need to reopen this PR - approved the other one.

2021-01-21 08:35 UTC, closed without merging