Correct path matching in CI-markdown
spacemeshos/go-spacemesh pull request #2284
Opened 2021-02-09 15:47 UTC by lrettig

## Motivation
This was wrong in #2272, so when only markdown files are changed, currently, CI fails to run completely.

This happened because the glob syntax [used by GitHub](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) slightly differs from that [used by picomatch](https://github.com/micromatch/picomatch#basic-globbing) (used under the hood in the library we're using here).

## Changes
- fix picomatch glob syntax to match all md files regardless of path

## Test Plan
N/A

2021-02-09 16:56 UTC, noamnelke requested changes
I think we also need to update line 20 in the same file. No?

2021-02-09 19:12 UTC, lrettig commented
> I think we also need to update line 20 in the same file. No?

No. Line 20 matches using the GitHub matching engine. It's confusing, but the syntax is slightly different. See the links I posted [above](https://github.com/spacemeshos/go-spacemesh/pull/2284#issue-570401456).

I'll a comment to this effect inline to make this a little clearer.

2021-02-10 12:34 UTC, noamnelke approved these changes

2021-02-10 12:35 UTC, noamnelke commented
Wow, confusing indeed...

2021-02-10 13:48 UTC, lrettig commented
bors merge

On Wed, Feb 10, 2021, 07:35 Noam Nelke <notifications@github.com> wrote:

> Wow, confusing indeed...
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/spacemeshos/go-spacemesh/pull/2284#issuecomment-776676894>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZJWNBXMXU2ONLKQ63FNS3S6J4QPANCNFSM4XLHPLTQ>
> .
>

2021-02-10 15:02 UTC, closed without merging