Terminate old hare processes if max concurrent processes are reached
spacemeshos/go-spacemesh pull request #2354
Opened 2021-03-28 21:19 UTC by sidsankhe

## Motivation

Closes #2303 

## Changes

## Test Plan

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

2021-03-31 00:20 UTC, lrettig requested changes

2021-03-31 00:20 UTC, lrettig commented on hare/broker.go
> +			id := b.minDeleted + 1
Don't overload the `id` variable here, it makes this code hard to read. Use a different name.

2021-03-31 00:20 UTC, lrettig commented on hare/broker.go
> +			delete(b.outbox, id)
Don't duplicate the code from the `Unregister` method. Refactor that method to create a new (internal) method that does not block, that you can call here directly.

2021-04-01 22:20 UTC, lrettig requested changes
One more change requested. Overall looks good. One more quick thing: are you 100% sure that this code is concurrency-safe? What if, e.g., `Register()` were called back to back in rapid succession, before the first task were completed? I think you either need to add some sort of concurrency safety or, if you're sure you don't need it, add a comment to this effect and explain why.

2021-04-01 22:20 UTC, lrettig commented on hare/broker.go
> +			instance := b.minDeleted + 1
I think you only want to unregister the oldest layer after the `b.isSynced(id)` check, below

2021-04-02 06:03 UTC, sidsankhe commented
The good thing with this code is that the tasks are submitted into a channel, and an event loop executes it synchronously. So even if `Register` were called quickly in succession, the tasks would be added to the event loop and would be executed synchronously.

2021-04-05 22:15 UTC, lrettig commented
> The good thing with this code is that the tasks are submitted into a channel, and an event loop executes it synchronously. So even if `Register` were called quickly in succession, the tasks would be added to the event loop and would be executed synchronously.

But the order isn't guaranteed, is it?

2021-04-05 23:42 UTC, sidsankhe commented
No, the order isn't guaranteed. However, since `Register` is called only on ticks, it should be very unlikely that there's a race condition such that it involves a later layer ID being Registered before an earlier layer ID. Even so, the `b.UpdateLatestLayer(id)` would panic if an earlier layer was trying to be Registered after a later layer. Do you think this check needs to be made stronger?

2021-04-06 23:49 UTC, lrettig commented
> No, the order isn't guaranteed. However, since `Register` is called only on ticks, it should be very unlikely that there's a race condition such that it involves a later layer ID being Registered before an earlier layer ID. Even so, the `b.UpdateLatestLayer(id)` would panic if an earlier layer was trying to be Registered after a later layer. Do you think this check needs to be made stronger?

I agree with your logic, it seems highly unlikely and therefore okay. Could you add an explanatory comment to this effect to the code?

2021-04-13 00:22 UTC, lrettig approved these changes
tweaked the comment wording slightly, otherwise lgtm

2021-04-13 17:06 UTC, sidsankhe commented
bors merge

2021-04-13 18:19 UTC, closed without merging