Grpc graceful shutdown
spacemeshos/go-spacemesh pull request #2436
Opened 2021-05-27 11:28 UTC by countvonzero

## Motivation

allow grpc server to shutdown gracefully - allow any in-flight requests to complete and return status code Unavailable for any new requests.

## Changes

for grpc/http servers, the graceful shutdown can block for a while. launch the shutdown routine and shutdown other components before waiting for grpc/http servers to finish shutting down.

## Test Plan

make test

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

2021-06-01 14:28 UTC, noamnelke reviewed
There's a possible problem that I see. Maybe it's not a problem, if you thought it through, lmk.

Since we issue the shutdown commands for the JSON and gRPC servers in goroutines, there's no guarantee that the JSON server will receive the command first. So there's a possible case where the gRPC server is already down, while the JSON server is still up. What happens when we call an endpoint on the JSON server? I assume it either errors or times out. It could be fine, especially if it's a rare condition. Just want to make sure it won't cause a panic or some other undesirable outcome.

What could be even worse is if we stop other services while the gRPC server is still up. Again could be fine (not sure it is) but it's even harder to make sure of this.

Am I overthinking this? Or could it be better to leave the shutdown process synchronous, even if it takes longer? What could help the decision is to know how long it currently takes to shut down the services after the gRPC server. If it's a couple of seconds or less then I vote to keep everything synchronous.

2021-06-01 14:28 UTC, noamnelke commented on cmd/node/node.go
> +			log.Info("stopping grpc service")
Not your fault, but let's remove this redundant log.
https://github.com/spacemeshos/go-spacemesh/blob/5d488e5d4bfdd85a0f316624b1d4679e40e8cfd0/api/grpcserver/grpc.go#L62

In the JSON server this log is a DEBUG, so either make it an INFO and remove from here as well, or make it DEBUG in the gRPC server and leave both here. Let's just be consistent.

2021-06-02 01:21 UTC, lrettig requested changes
I'm curious why you chose to attack the grpc services and only the grpc services. Other services, like sync and p2p, could also hang while, e.g., waiting for a send attempt to timeout for as long as 30 secs.

I sort of agree with Noam's concerns: without strict control on the order that services are shut down, there's the possibility of getting into a weird state where service A, which depends on service B, is still running while B has been shut down.

It seems to me like the right way to attach this is to switch to using context, as we discussed - to fire off a single `CancelFunc` so that all services receive the message at the same time.

2021-06-02 01:21 UTC, lrettig commented on cmd/node/node.go
> +	gsync "sync"
This is a nitpick, but I'd rather you "import as" our sync library than the standard sync lib, for readability. Call it "syncer" maybe. `gsync` sounds like something google-related!

2021-08-28 07:29 UTC, avive commented
It is awesome to see grpc improvements - but this issue has SO much more impact on the end users experience than this one: #2533 - I hope it can be implemented soon in a sprint and in time for 0.2 open devnet....

2022-06-22 22:28 UTC, countvonzero commented
closing as the PR is too old.

2022-06-22 22:28 UTC, closed without merging