set cgo ldflafs to environment, use $(make ldflags) command
spacemeshos/go-spacemesh pull request #2600
Opened 2021-07-27 15:02 UTC by sudachen

It sets CGO_LDFLAGS environment variable. Use it before start go test ... 

```
[sudachen/go-spacemesh|ldflags] ../go-spacemesh$ $(make ldflags)
[sudachen/go-spacemesh|ldflags] ../go-spacemesh$ go test ./activation
ok  	github.com/spacemeshos/go-spacemesh/activation	25.937s
```

2021-07-27 15:10 UTC, noamnelke approved these changes

2021-07-27 15:14 UTC, noamnelke commented
@sudachen shouldn't we call the exported variable `CGO_TEST_LDFLAGS`?

2021-07-27 22:18 UTC, noamnelke requested changes
Let's not merge this.

I just learned about `go env -w` - read about it [here](https://pkg.go.dev/cmd/go#hdr-Print_Go_environment_information).
This means we can set the default value for `CGO_LDFLAGS` in a global way. We can make the ldflags make command call
```
go env -w CGO_LDFLAGS="$(CGO_TEST_LDFLAGS)"
```
Actually we can call it something more generic, like `set-go-env`. As long as we run this make command before using `go build`/`go test` it Just Works.

Regarding GoLand - it has a feature where you can always run one config before running another - so this will even prevent devs from forgetting to run the make command.

![image](https://user-images.githubusercontent.com/776358/127234771-8484f780-c239-4026-a714-d371f616fbb0.png)

2021-08-03 06:02 UTC, dshulyak commented
would be nice if we can merge some version of this change

2021-08-03 12:00 UTC, noamnelke commented
> would be nice if we can merge some version of this change

I'll do something now.

2021-08-05 13:52 UTC, noamnelke commented
Superseded by #2627

2021-08-05 13:52 UTC, closed without merging