P2p gossip v2
spacemeshos/go-spacemesh pull request #265
Opened 2018-11-15 11:13 UTC by y0sher

Fixes some issues from previous gossip, handling some cr comments. 
next iteration is going to handle the rest.

2018-11-18 14:35 UTC, almogdepaz commented on p2p/dht/bootstrap.go
>  			d.rt.Size(req)
i think its more readable if this inits and returns a chan

2018-11-18 16:28 UTC, y0sher commented on p2p/gossip/protocol.go
> +	spew.Dump(s.peers)
```suggestion
	s.Info(spew.Sdump(s.peers))
```

2018-11-18 16:29 UTC, zalmen requested changes

2018-11-18 16:29 UTC, zalmen commented on p2p/dht/bootstrap.go
>  	i := 0
rename to something better

2018-11-18 16:29 UTC, zalmen commented on p2p/dht/bootstrap.go
> +				rnd, _ := crypto.GetRandomBytes(32)
add a todo to consider choosing a random key that is close to the local id

2018-11-18 16:29 UTC, zalmen commented on p2p/dht/bootstrap.go
> +				continue
add a comment explaining what happened here

2018-11-18 16:29 UTC, zalmen commented on p2p/dht/bootstrap.go
> +				continue
also, consider if you need this flow also in the case where you queried a random peer and found it

2018-11-18 16:29 UTC, zalmen commented on p2p/dht/bucket.go
> +			continue
remove the continue and the e = e.Next() from within the for loop

2018-11-18 16:29 UTC, zalmen commented on p2p/dht/table.go
> +	buckets := []Bucket{}
Can't you set the capacity to be BucketCount?

2018-11-18 16:29 UTC, zalmen commented on p2p/dht/table.go
> +	if bucket.Len() > rt.bucketsize {
remove

2018-11-18 16:29 UTC, zalmen commented on p2p/dht/table.go
> +	if newBucket.Len() > rt.bucketsize {
can't happen since you first call split and then add the node

2018-11-18 16:29 UTC, zalmen commented on p2p/gossip/protocol.go
> +	msghash := fnv.New32()
check if you can store the fnv without creating it everytime

2018-11-18 16:29 UTC, zalmen commented on p2p/gossip/protocol.go
> +				dischann <- p.PublicKey().String()
IMO the correct feed for disconnecting peers should be ConnectionPool (via swarm or directly). It is better then deducing this from the send failure

2018-11-18 16:29 UTC, zalmen commented on p2p/gossip/protocol.go
>  	if _, ok := s.oldMessageQ[string(msg)]; ok {
use hash as key

2018-11-18 16:29 UTC, zalmen commented on p2p/gossip/protocol.go
>  	if _, ok := s.oldMessageQ[string(msg)]; ok {
also, you should think of an offline garbage collector to periodically clear this queue

2018-11-18 16:29 UTC, zalmen commented on p2p/gossip/protocol.go
> +		time.Sleep(NoResultsTimeout)
this logic should be handled by the caller of this method. The caller should decide whether or not it wishes to sleep and retry

2018-11-18 16:29 UTC, zalmen commented on p2p/gossip/protocol.go
> +	tm := time.NewTimer(time.Second * 20 * time.Duration(ndsLen))
since you're calling GetConnection in parallel the timeout shouldn't be multiply by ndsLen

2018-11-18 16:29 UTC, zalmen commented on p2p/gossip/protocol.go
> +		s.getMorePeers(s.config.RandomConnections - len(s.peers))
should be called by the caller and not recursively

2018-11-18 16:29 UTC, zalmen commented on p2p/gossip/protocol.go
> +func (s *Neighborhood) AddPeer(n node.Node, c net.Connection) {
Rename to AddIncomingPeer

2018-11-25 16:15 UTC, zalmen approved these changes

2018-11-25 16:15 UTC, zalmen commented on p2p/gossip/protocol.go
> +			if cne.err != nil || cne.n == node.EmptyNode {
is it possible that cne.err == nil and cne.n == node.EmptyNode?

2018-11-25 16:15 UTC, zalmen commented on p2p/gossip/protocol.go
> +			close(aborted)
I don't see anyone listening to the aborted channel, what is it used for?

2018-11-25 16:15 UTC, zalmen commented on p2p/gossip/protocol.go
> +		if len(s.peers) >= s.config.RandomConnections {
shouldn't there be an else? What happen if you didn't get enough peers?

2018-11-25 17:22 UTC, merged