Libp2p poc
spacemeshos/go-spacemesh pull request #2801
Opened 2021-09-20 07:25 UTC by dshulyak

## Motivation

Closes #

## Changes

## Test Plan

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

2021-10-15 07:38 UTC, dshulyak commented on blocks/blocks.go
> +	ctx = log.WithNewRequestID(ctx)
remove this

2021-10-15 07:38 UTC, dshulyak commented on blocks/blocks.go
> +		return pubsub.ValidationReject
s/Reject/Ignore

2021-10-15 07:38 UTC, dshulyak commented on cmd/hare/hare.go
> +	hareI := hare.New(app.Config.HARE, "", nil, app.sgn, types.NodeID{Key: app.sgn.PublicKey().String(), VRFPublicKey: []byte{}}, IsSynced, &mockBlockProvider{}, hareOracle, uint16(app.Config.LayersPerE
fix

2021-10-15 07:38 UTC, dshulyak commented on cmd/node/multi_node.go
> +	smApp.gatewaySvc = grpcserver.NewGatewayService(nil)
host

2021-10-15 07:38 UTC, dshulyak commented on cmd/node/node.go
> +		if t != reflect.TypeOf(big.Rat{}) {
rebase issue?

2021-10-15 07:38 UTC, dshulyak commented on Makefile
> -dockerrun-sync:
submit with separate pr

2021-10-15 07:38 UTC, dshulyak commented on api/grpcserver/http_server.go
> +		if err := gw.RegisterGatewayServiceHandlerServer(ctx, mux, gwservice); err != nil {
refactor and submit as a separate PR. gateway doesn't have to maintain a connection with grpc this way

2021-10-15 07:38 UTC, dshulyak commented on blocks/blocks_test.go
> +	r.EqualError(err, errNoActiveSet.Error())
?

2021-10-15 07:38 UTC, dshulyak commented on cmd/base.go
> +func bigRatDecodeFunc() mapstructure.DecodeHookFunc {
this is duplicated. also can't recall why it was needed

2021-10-15 07:38 UTC, dshulyak commented on fetch/fetch.go
> -	retries := 0
revert this change. if at the time of request connection doesn't exist this will try to pick another connection. not sure if it is necessary, as there is very little lag between data returned by Peers and actual connections, but to minimize changes

2021-10-15 07:38 UTC, dshulyak commented on hare/broker.go
> +type msgRPC struct {
pass msg context here as well, so that request id can be embedded early

2021-10-15 07:38 UTC, dshulyak commented on layerfetcher/layers.go
> +	atxsrv, blocksrv, beaconsrv *server.Server
beaconsrv is a leftover

2021-10-15 07:38 UTC, dshulyak commented on miner/block_builder.go
> +				bytes, err := types.InterfaceToBytes(blk)
use go func() {} to minimize amount of changes. even though it is unnecessary here

2021-10-19 17:08 UTC, dshulyak commented
bors try

2021-10-19 21:00 UTC, nkryuchkov requested changes
Great work! I have some minor change requests

2021-10-19 21:00 UTC, nkryuchkov commented on .golangci.yml
> +#   - wrapcheck
Why do you want to disable it?

2021-10-19 21:00 UTC, nkryuchkov commented on api/grpcserver/grpcserver_test.go
> +				data := received
This looks like a potential data race. Do we need to guard `received` with a mutex? Also, can we get rid of the `data` variable?

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/base.go
> +func bigRatDecodeFunc() mapstructure.DecodeHookFunc {
This is needed to decode `*big.Rat`'s in the `tortoisebeacon` package. As you said, we need to extract a common decoding function or even a common function for parsing config.

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/base.go
> +		if t != reflect.TypeOf(big.Rat{}) {
Why is it `big.Rat{}` instead of `&big.Rat{}`?

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/multi_node_sim/config.toml
> +target-outbound = 2
Why was it changed from 10 to 2?

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/node/app_test.go
> +	before := make([]byte, 1<<16)
We have two variables with stack traces: `before` and `buf`. They don't look similar and aren't descriptive enough. Can we rename them?

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/node/multi_node.go
> +	cfg.P2P.TargetOutbound = 0
As we don't have the `sync` module anymore, do we need to update the comment above?

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/node/node.go
> +		if t != reflect.TypeOf(big.Rat{}) {
Why do we need to remove the pointer type? The tortoise beacon config has pointer types and I tested it with pointers. Does it work correctly now?

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/node/multi_node.go
> +func InitSingleInstance(lg log.Log, cfg config.Config, i int, genesisTime string, storePath string, rolacle *eligibility.FixedRolacle,
Not in the scope of your PR, but can we change `genesisTime`'s type to `time.Time`? The `string` type looks weird

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/node/node.go
> +		return
Should we log the error?

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/root.go
> +		config.P2P.Flood, "flood created messages to all peers (true by default. disable to lower traffic reqiurements)")
```suggestion
		config.P2P.Flood, "flood created messages to all peers (true by default; disable to lower traffic requirements)")
```
```suggestion
		config.P2P.Flood, "flood created messages to all peers (true by default, disable to lower traffic requirements)")
```

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/root.go
> +		config.P2P.NetworkID, "network-id to participate int")
`participate int` looks like a typo

2021-10-19 21:00 UTC, nkryuchkov commented on cmd/root.go
> +		"high watermark for the number of connections. once reached connections are pruned until low watermark remains")
```suggestion
		"high watermark for the number of connections; once reached, connections are pruned until low watermark remains")
```
```suggestion
		"high watermark for the number of connections, once reached connections are pruned until low watermark remains")
```

2021-10-19 21:00 UTC, nkryuchkov commented on config/config.go
> +	conf.P2P = lp2p.Default()
Perhaps `DefaultConfig`? `Default` doesn't look consistent

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/bootstrap/bootstrap.go
> +				panic("event must be of type EventHandshakeComplete")
Can someone send a malformed event that triggers node panic?

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/bootstrap/bootstrap.go
> +		return fmt.Errorf("unexpected error dureing bootstrap: %w", err)
```suggestion
		return fmt.Errorf("unexpected error during bootstrap: %w", err)
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/bootstrap/bootstrap.go
> +	return
Can we remove it?

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/bootstrap/bootstrap.go
> +func (b *Bootstrap) triggerBootstrap(ctx context.Context, limit chan struct{}, total, outbound int) {
Do we need `total`? It's not used

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/bootstrap/bootstrap_test.go
> +		require.FailNow(t, "timedout on waiting for a call to Bootstrap")
```suggestion
		require.FailNow(t, "timed out on waiting for a call to Bootstrap")
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/bootstrap/bootstrap_test.go
> +			require.FailNow(t, "timedout on waiting for bootctx cancellation")
```suggestion
			require.FailNow(t, "timed out on waiting for bootctx cancellation")
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/handshake/handshake.go
> +						_ = h.h.Network().ClosePeer(id.Peer)
Don't we need a debug log for it?

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/identity.go
> +		return nil, fmt.Errorf("faile to unmarshal file content from %s into %+v: %w", path, info, err)
```suggestion
		return nil, fmt.Errorf("failed to unmarshal file content from %s into %+v: %w", path, info, err)
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/identity.go
> +	return nil, fmt.Errorf("failed to read key from disk: %w", err)
If this returns an error, somewhere above the call stack we'll get a log like `Failed to start the node. See logs for details err=failed to initialize p2p host: failed to read key from disk: failed to read file %s: %w`, so words `failed to` will be duplicated a lot of times and the log will be unreadable. I suggest removing verbs (`failed to`/`cannot`/`unable to` etc) from all wrapped errors and having them only where we log an error.

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/addrbook.go
> +// peers on the network. based on bitcoin's addrBook.
```suggestion
// peers on the network; based on bitcoin's addrBook.
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/addrbook.go
> +// Good marks the given address as good.  To be called after a successful
```suggestion
// Good marks the given address as good. To be called after a successful
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/addrbook.go
> +// connection and version exchange.  If the address is unknown to the address
```suggestion
// connection and version exchange. If the address is unknown to the address
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/crawler.go
> +			r.logger.Debug("crawl finished. no more servers to query")
```suggestion
			r.logger.Debug("crawl finished; no more servers to query")
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/discovery.go
> +			return 0, fmt.Errorf("port %d cant fit into uint16 %d", port, math.MaxUint16)
```suggestion
			return 0, fmt.Errorf("port %d can't fit into uint16 %d", port, math.MaxUint16)
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/discovery.go
> +		return uint16(port), nil //nolint
What linter complains here? We can disable a specific linter by `nolint: linter_name`

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/discovery_test.go
> +		require.True(t, len(h.Network().Conns()) > 1,
```suggestion
		require.Greater(t, len(h.Network().Conns()), 1,
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/known_address.go
> +// Chance returns the selection probability for a known address.  The priority
```suggestion
// Chance returns the selection probability for a known address. The priority
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/store.go
> +// loadPeers loads the known address from the saved file.  If empty, missing, or
```suggestion
// loadPeers loads the known address from the saved file. If empty, missing, or
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/store.go
> +	// First we make a serialisable datastructure so we can encode it to
```suggestion
	// First we make a serializable data structure so we can encode it to
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/pubsub/pubsub.go
> +type PublisherSubscriber interface {
Nit: Should it be `PublishSubscriber` according to the naming convention? (e.g. https://pkg.go.dev/io#ReadWriteCloser)

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/handshake/handshake.go
> +	h.emitter.Emit(EventHandshakeComplete{PID: pid, Direction: stream.Conn().Stat().Direction})
What if it returns an error?

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/store.go
> +		return fmt.Errorf("error opening file: %v", err)
```suggestion
		return fmt.Errorf("error opening file: %w", err)
```

2021-10-19 21:00 UTC, nkryuchkov commented on lp2p/peerexchange/store.go
> +		return fmt.Errorf("error reading %s: %v", path, err)
```suggestion
		return fmt.Errorf("error reading %s: %w", path, err)
```

2021-10-19 21:11 UTC, nkryuchkov commented on .env
> -SMESH_RANDCON=8
It's still left in `./docker-compose.yml`

2021-10-19 21:11 UTC, nkryuchkov commented on .env
> +SMESH_TARGET_OUTBOUND=8
It's missing in `./docker-compose.yml`. Could you please also add a comment above?

2021-10-19 21:11 UTC, nkryuchkov commented on cmd/root.go
> +	cmd.PersistentFlags().IntVar(&config.P2P.TargetOutbound, "target-outbound",
It's missing in `./docker-compose.yml`. Also, `randcon` is still present in both `./docker-compose.yml` and `./config.toml`.

2021-10-20 02:54 UTC, dshulyak commented on .golangci.yml
> +#   - wrapcheck
it errors on status.Error and ctx.Err(). i wasn't able to disable this error with exceptions, but one is the external grpc error and another is a common thing that is ugly to wrap

2021-10-20 02:57 UTC, dshulyak commented on cmd/base.go
> +		if t != reflect.TypeOf(big.Rat{}) {
i think it was due to the update of mapstructure (or some other library) that comparison with pointer wasn't working correctly. but right it was long ago and i need to double check

2021-10-20 02:58 UTC, dshulyak commented on cmd/multi_node_sim/config.toml
> +target-outbound = 2
as you see there is no randcon now. target-outbound is closer to randcon in logic, but it really doesn't matter i can set it to 10

2021-10-20 02:59 UTC, dshulyak commented on cmd/node/multi_node.go
> +	cfg.P2P.TargetOutbound = 0
why we don't have sync module?

2021-10-20 03:01 UTC, dshulyak commented on lp2p/identity.go
> +	return nil, fmt.Errorf("failed to read key from disk: %w", err)
doesn't make sense to me, they shouldn't be wrapped then. how would you reword this error so that it makes sense?

2021-10-20 03:31 UTC, dshulyak commented on api/grpcserver/grpcserver_test.go
> +				data := received
there is wg on top

2021-10-20 03:37 UTC, dshulyak commented on cmd/base.go
> +		if t != reflect.TypeOf(big.Rat{}) {
with pointer it fails

2021-10-20T06:37:27.663+0300	ERROR	00000.defaultLogger	Failed to parse config	{"errmsg": "2 error(s) decoding:\n\n* 'tortoise-beacon.tortoise-beacon-q' expected a map, got 'string'\n* 'tortoise-beacon.tortoise-beacon-theta' expected a map, got 'string'", "name": ""}
2021-10-20T06:37:27.663+0300	ERROR	00000.defaultLogger	can't load config file	{"errmsg": "unmarshal viper: 2 error(s) decoding:\n\n* 'tortoise-beacon.tortoise-beacon-q' expected a map, got 'string'\n* 'tortoise-beacon.tortoise-beacon-theta' expected a map, got 'string'", "name": ""}

2021-10-20 04:22 UTC, dshulyak commented on .env
> +SMESH_TARGET_OUTBOUND=8
docker-compose config file is outdated. we should probably just remove it. if we nobody uses that we can as well remove it instead of fixing

2021-10-20 04:22 UTC, dshulyak commented on cmd/node/multi_node.go
> +	cfg.P2P.TargetOutbound = 0
we don't have sync binary. everything else is the same

2021-10-20 04:22 UTC, dshulyak commented on cmd/node/multi_node.go
> +func InitSingleInstance(lg log.Log, cfg config.Config, i int, genesisTime string, storePath string, rolacle *eligibility.FixedRolacle,
as you said, not in the scope of my PR :)

2021-10-20 04:22 UTC, dshulyak commented on cmd/root.go
> +	cmd.PersistentFlags().IntVar(&config.P2P.TargetOutbound, "target-outbound",
docker-compose is outdated. config.toml seems as well outdated (coinbase was renamed long time ago), if we are not using it, it can be as well removed

2021-10-20 04:29 UTC, dshulyak commented
bors try

2021-10-20 09:53 UTC, dshulyak commented
bors try

2021-10-20 10:29 UTC, dshulyak commented on cmd/multi_node_sim/config.toml
> +target-outbound = 2
i will keep it as two, to preserve original behavior

2021-10-20 11:51 UTC, nkryuchkov commented on .golangci.yml
> +#   - wrapcheck
Thanks, I'll try to fix it

2021-10-20 11:51 UTC, nkryuchkov commented on cmd/base.go
> +		if t != reflect.TypeOf(big.Rat{}) {
I see, thanks

2021-10-20 11:52 UTC, nkryuchkov commented on cmd/node/multi_node.go
> +	cfg.P2P.TargetOutbound = 0
Yeah, sorry, now I see

2021-10-20 11:54 UTC, nkryuchkov commented on cmd/node/node.go
> +		if t != reflect.TypeOf(big.Rat{}) {
Resolved in https://github.com/spacemeshos/go-spacemesh/pull/2801#discussion_r732391808

2021-10-20 11:57 UTC, nkryuchkov commented on lp2p/identity.go
> +	return nil, fmt.Errorf("failed to read key from disk: %w", err)
In my opinion, `Failed to start the node. See logs for details err=initialize p2p host: read key from disk: read file %s: %w` would be more readable, so I'd change this to
```suggestion
	return nil, fmt.Errorf("read key from disk: %w", err)
```

2021-10-20 12:00 UTC, nkryuchkov commented on cmd/node/multi_node.go
> +func InitSingleInstance(lg log.Log, cfg config.Config, i int, genesisTime string, storePath string, rolacle *eligibility.FixedRolacle,
ok, let's leave it as is then

2021-10-20 14:48 UTC, dshulyak commented
bors try

2021-10-21 05:21 UTC, dshulyak commented
bors try

2021-10-21 05:32 UTC, dshulyak commented on cmd/node/app_test.go
> +	before := make([]byte, 1<<16)
we can, but i don't want to refactor a lot of unrelated code in this pr, i will just remove my change

2021-10-21 05:33 UTC, dshulyak commented on cmd/node/node.go
> +		return
WaitPeers errors only on ctx cancellation

2021-10-21 05:33 UTC, dshulyak commented on cmd/node/node.go
> +		return
also there was no log before, if it is needed then not in this pr

2021-10-21 05:40 UTC, dshulyak commented on lp2p/bootstrap/bootstrap.go
> +				panic("event must be of type EventHandshakeComplete")
event subsystem is not connected to any node, if this occurs that would a programmer mistake

2021-10-21 05:59 UTC, dshulyak commented on config/config.go
> +	conf.P2P = lp2p.Default()
done

2021-10-21 05:59 UTC, dshulyak commented on lp2p/pubsub/pubsub.go
> +type PublisherSubscriber interface {
done

2021-10-21 05:59 UTC, dshulyak commented on lp2p/peerexchange/store.go
> +	// First we make a serialisable datastructure so we can encode it to
thats wasn't my code. i will remove this comment, as such stuff is self explanatory

2021-10-21 05:59 UTC, dshulyak commented on lp2p/identity.go
> +	return nil, fmt.Errorf("failed to read key from disk: %w", err)
done

2021-10-21 05:59 UTC, dshulyak commented on lp2p/handshake/handshake.go
> +	h.emitter.Emit(EventHandshakeComplete{PID: pid, Direction: stream.Conn().Stat().Direction})
added a log

2021-10-21 05:59 UTC, dshulyak commented on lp2p/handshake/handshake.go
> +						_ = h.h.Network().ClosePeer(id.Peer)
not sure, i will skip it for now

2021-10-21 06:42 UTC, dshulyak commented
bors try

2021-10-21 07:06 UTC, dshulyak commented
bors try

2021-10-21 07:35 UTC, dshulyak commented
bors try

2021-10-21 09:31 UTC, countvonzero requested changes
i only reviewed half of this. will continue tomorrow.
two general feedback
- rename lp2p to p2p. i think for readers p2p is more intuitive
- can we remove sync system test in a separate PR

2021-10-21 09:31 UTC, countvonzero commented on activation/atxdb.go
> +	// FIXME(dshulyak) this should not be defined in database
personally i think the whole gossip handling does not belong here. atxdb should focus on just data read/write.
i'd like these gossip handling code moved to its own file (like poetlistener.go), or to activation.go

2021-10-21 09:31 UTC, countvonzero commented on activation/poetlistener.go
> +	return pubsub.ValidationAccept
should still propagate this msg even if `storeProof()` failed

2021-10-21 09:31 UTC, countvonzero commented on api/grpcserver/grpcserver_test.go
>  	broadcasted  []byte
all the fields are not used.

2021-10-21 09:31 UTC, countvonzero commented on api/grpcserver/node_service.go
> +func (s NodeService) Close() {}
can we rm this all together?

2021-10-21 09:31 UTC, countvonzero commented on cmd/base.go
> +		bigRatDecodeFunc(),
why are these extra hooked required? what's missing from the vanilla `Unmarshal()` with current config?

2021-10-21 09:31 UTC, countvonzero commented on cmd/base.go
> +func bigRatDecodeFunc() mapstructure.DecodeHookFunc {
i don't understand. what's wrong with the current parsing? and why is it parsing everything into big.Rat?

2021-10-21 09:31 UTC, countvonzero commented on cmd/hare/hare.go
> +	log.SetupGlobal(logger)
can this be removed?

2021-10-21 09:31 UTC, countvonzero commented on cmd/node/app_test.go
> +		suite.T().Cleanup(func() { _ = wrapped.Stop() })
i'm not 100% sure, do you need to capture `wrapped` into a new variable here?

2021-10-21 09:31 UTC, countvonzero commented on cmd/node/node.go
>  type TortoiseBeaconService interface {
i don't understand why we need to need to declare an extra interface for this. why not just use TortoiseBeacon directly?

2021-10-21 09:31 UTC, countvonzero commented on cmd/node/node.go
>  func bigRatDecodeFunc() mapstructure.DecodeHookFunc {
this is confusing. what's the difference btwn this one and the one in base.go?

2021-10-21 09:31 UTC, countvonzero commented on cmd/node/node.go
> +func (s *syncHandler) Handle(ctx context.Context, _ lp2p.Peer, _ []byte) pubsub.ValidationResult {
ctx not used either.

2021-10-21 09:31 UTC, countvonzero commented on cmd/node/node.go
> +	app.host.Register(weakcoin.GossipProtocol, pubsub.ChainGossipHandler(syncValidator.Handle, wc.HandleProposal))
is this a change of behavior? i don't remember weakcoin protocol requires this.

2021-10-21 09:31 UTC, countvonzero commented on cmd/node/node.go
> +		pubsub.ChainGossipHandler(syncValidator.Handle, tBeacon.HandleSerializedFollowingVotingMessage))
this is a change of protocol. 
- before
  - check for `synced` state at the beginning of the protocol
  - once we enter into protocol, we continue until it finishes
- after 
  - check for `synced` state at the beginning of the protocol
  - check for `gossipSync` state before receiving every gossip messages
  
this means we will leave the protocol unfinished if we go out of sync in the middle of the protocol.
i am guessing it's ok but rather untested. maybe we can check whether TortoiseBeacon is `inProtocol` or not instead. but for simplicity, i think we should just follow the model of hare messages.

2021-10-21 09:31 UTC, countvonzero commented on cmd/node/node.go
> +	app.host.Register(blocks.NewBlockProtocol, pubsub.ChainGossipHandler(syncValidator.Handle, blockListener.HandleBlock))
can we put all the app.host.Register into a separate function RegisterGossipHandlers() so we can have a holistic view of them, and to see clearly what gossip messages require sync state and what don't

2021-10-21 09:31 UTC, countvonzero commented on cmd/node/node.go
> -	gossipListener := service.NewListener(swarm, layerFetch, newSyncer.ListenToGossip, app.addLogger(GossipListener, lg))
const `GossipListener` can be removed

2021-10-21 09:35 UTC, dshulyak commented on cmd/node/node.go
>  type TortoiseBeaconService interface {
but is it my change?

2021-10-21 09:35 UTC, dshulyak commented on cmd/hare/hare.go
> +	log.SetupGlobal(logger)
logging setup in hare wasn't working well

2021-10-21 09:36 UTC, dshulyak commented on activation/poetlistener.go
> +	return pubsub.ValidationAccept
honestly i just changed related stuff

2021-10-21 09:38 UTC, dshulyak commented on cmd/node/node.go
> +		pubsub.ChainGossipHandler(syncValidator.Handle, tBeacon.HandleSerializedFollowingVotingMessage))
but this condition was hidden in p2p layer, i don't think that there is a change

2021-10-21 09:45 UTC, dshulyak commented on cmd/node/node.go
> +	app.host.Register(weakcoin.GossipProtocol, pubsub.ChainGossipHandler(syncValidator.Handle, wc.HandleProposal))
we have this condition in p2p layer

2021-10-21 09:46 UTC, dshulyak commented on cmd/node/node.go
> +func (s *syncHandler) Handle(ctx context.Context, _ lp2p.Peer, _ []byte) pubsub.ValidationResult {
it is implementation to satisfy required interface

2021-10-21 09:46 UTC, dshulyak commented on cmd/node/node.go
>  func bigRatDecodeFunc() mapstructure.DecodeHookFunc {
extracted to separate module

2021-10-21 10:57 UTC, dshulyak commented
bors try

2021-10-21 12:04 UTC, nkryuchkov commented on lp2p/identity.go
> +	return nil, fmt.Errorf("failed to read key from disk: %w", err)
thanks

2021-10-21 12:08 UTC, nkryuchkov commented on lp2p/peerexchange/store.go
> +	// First we make a serialisable datastructure so we can encode it to
I didn't think that a significant part of code was copied. Feel free to ignore my comments where you just copied the old code

2021-10-21 12:09 UTC, dshulyak commented
bors try

2021-10-21 12:28 UTC, nkryuchkov approved these changes

2021-10-21 13:05 UTC, dshulyak commented
bors try

2021-10-22 02:24 UTC, dshulyak commented on cmd/hare/hare.go
> +	log.SetupGlobal(logger)
and i needed it for debug at some pointer, you can see original logger initialization below.
not sure why is it a problem

2021-10-22 02:24 UTC, dshulyak commented on cmd/node/app_test.go
> +		suite.T().Cleanup(func() { _ = wrapped.Stop() })
h is an interface and wrapped is not, surely i can cast wrapped to h interface, but h interface is missing Stop method

2021-10-22 02:33 UTC, dshulyak commented on cmd/node/node.go
> +	app.host.Register(blocks.NewBlockProtocol, pubsub.ChainGossipHandler(syncValidator.Handle, blockListener.HandleBlock))
i would rather let every component register gossip handler

2021-10-22 02:36 UTC, dshulyak commented
bors try

2021-10-22 02:39 UTC, dshulyak commented
bors try

2021-10-22 02:50 UTC, dshulyak commented on cmd/node/node.go
> +func (s *syncHandler) Handle(ctx context.Context, _ lp2p.Peer, _ []byte) pubsub.ValidationResult {
ah you meant _

2021-10-22 02:54 UTC, dshulyak commented
bors try

2021-10-22 03:34 UTC, dshulyak commented
for some reason can't reply to the next comment in place

> i don't understand. what's wrong with the current parsing? and why is it parsing everything into big.Rat?

mapstructure doesn't know how to parse into big.Rat, that's why we have that function. it wasn't introduced in this PR, it was first introduced for tortoise beacon and later used in tortoise as well.

it doesn't parse everything into bit.Rat, it checks if the type is a big.Rat and then parses value according to that function logic.

in this pr i also used this in cmd/base, because otherwise config unmarshalling was failing when it was parsed outside of the cmd/node. afair it was due to the update of the mapstructure library, that got update when i fetched libp2p deps

2021-10-22 04:15 UTC, dshulyak commented
bors try

2021-10-22 05:05 UTC, countvonzero reviewed
review part II. i have reviewed everything but lp2p package

2021-10-22 05:05 UTC, countvonzero commented on cmd/node/node.go
>  type TortoiseBeaconService interface {
no. not your change. but you did have to change something for this so might as well remove it. not important tho.

2021-10-22 05:05 UTC, countvonzero commented on cmd/node/node.go
> +		pubsub.ChainGossipHandler(syncValidator.Handle, tBeacon.HandleSerializedFollowingVotingMessage))
you are right. it was built-in in the gossip listener.

2021-10-22 05:05 UTC, countvonzero commented on hare/broker.go
> +func newBroker(pid peer.ID, eValidator validator, stateQuerier StateQuerier, syncState syncStateFunc, layersPerEpoch uint16, limit int, closer util.Closer, log log.Log) *Broker {
broker.pid wasn't assigned to this pid

2021-10-22 05:05 UTC, countvonzero commented on hare/broker.go
> +	logger := b.WithContext(ctx).WithFields(log.FieldNamed("latest_layer", types.LayerID(b.latestLayer)))
no need to type cast b.latestLayer

2021-10-22 05:05 UTC, countvonzero commented on timesync/peersync/sync.go
> +		s.log.With().Warning("can't encode response", log.Err(err))
why not keep the original panic?

2021-10-22 05:05 UTC, countvonzero commented on timesync/peersync/sync.go
> +	if _, err := codec.DecodeFrom(stream, &request); err != nil {
is the change to codec here required for libp2p lib?

2021-10-22 05:05 UTC, countvonzero commented on timesync/peersync/sync.go
> +			stream, err := s.h.NewStream(network.WithNoDial(ctx, "existing connection"), pid, protocol.ID(protocolName))
no need for protocol.ID casting.

2021-10-22 05:05 UTC, countvonzero commented on timesync/peersync/sync.go
> +	h.SetStreamHandler(protocol.ID(protocolName), sync.streamHandler)
no need for protocol.ID casting.

2021-10-22 05:05 UTC, countvonzero commented on timesync/peersync/sync.go
> +			_ = stream.SetDeadline(s.time.Now().Add(s.config.RoundTimeout))
defer stream.Close()?

2021-10-22 05:05 UTC, countvonzero commented on tortoisebeacon/tortoise_beacon.go
> +			return fmt.Errorf("broadcast: %w", err)
i thought returning error here cancel the errgroup. is that intended?
besides, i don't see any caller holding a lock while calling `sendToGossip`. is this needed?

2021-10-22 05:05 UTC, countvonzero commented on timesync/peersync/sync.go
> +	defer stream.SetDeadline(time.Time{})
why is this needed? is the underlying stream being reused?

2021-10-22 05:05 UTC, countvonzero commented on tortoisebeacon/weakcoin/weak_coin.go
> +	if err := wc.publisher.Publish(ctx, GossipProtocol, msg); err != nil {
should this be in a separate goroutine as well?

2021-10-22 05:19 UTC, dshulyak commented on tortoisebeacon/weakcoin/weak_coin.go
> +	if err := wc.publisher.Publish(ctx, GossipProtocol, msg); err != nil {
i know that weakcoin won't deadlock, that's why no goroutine

2021-10-22 05:20 UTC, dshulyak commented on tortoisebeacon/tortoise_beacon.go
> +			return fmt.Errorf("broadcast: %w", err)
yes it was intended, as Publish should not error in general

as for goroutine, i wasn't sure that tortoise beacon will not deadlock as there is a lot of synchronization and buffering using channels, so i decided to add goroutine for safety

2021-10-22 05:21 UTC, dshulyak commented on timesync/peersync/sync.go
> +	if _, err := codec.DecodeFrom(stream, &request); err != nil {
no, but this is more efficient way to decode. instead of decoding into buffer and then into struct, i am decoding incrementally into struct

2021-10-22 05:21 UTC, dshulyak commented on timesync/peersync/sync.go
> +		s.log.With().Warning("can't encode response", log.Err(err))
because encoder writes to the stream

2021-10-22 05:27 UTC, dshulyak commented on timesync/peersync/sync.go
> +	defer stream.SetDeadline(time.Time{})
i wasn't sure that deadline is not applied to the underlying connection in some muxers, will double check if it is not applied with yamux and remove it if it is not

2021-10-22 05:38 UTC, dshulyak commented on timesync/peersync/sync.go
> +	if _, err := codec.DecodeFrom(stream, &request); err != nil {
in this case it is more about simplicity, rather then efficiency, as the struct is 8 bytes

2021-10-22 06:53 UTC, dshulyak commented
bors try

2021-10-22 08:23 UTC, dshulyak commented
bors try

2021-10-22 09:21 UTC, dshulyak commented
bors try

2021-10-22 10:14 UTC, dshulyak commented
in the last test kibana failed to setup on time, but otherwise tests look stable

2021-10-22 11:23 UTC, countvonzero commented on lp2p/bootstrap/bootstrap.go
> +			if _, exist := peers[hs.PID]; exist {
what does this mean? is it expected to be notified multiple times of the same event? or that the node maybe complete handshake with the same peer multiple times?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/bootstrap/bootstrap.go
> +				b.host.ConnManager().TagPeer(hs.PID, "outbound", 100)
what is the weight of inbound? 0?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/bootstrap/bootstrap.go
> +			if exist && b.host.Network().Connectedness(pid) == network.NotConnected {
why is the extra check on network.NotConnected required? 
are connection still useful when it's in the other states (CannotConnect and CanConnect)?
and is it possible to be disconnected with the state being Connected?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/bootstrap/peers.go
> +func WithNodeStatesReporter(f func()) Opt {
is this used?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/bootstrap/peers.go
> +func NewPeers(h host.Host, opts ...Opt) *Peers {
private to package?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/bootstrap/peers.go
> +	nodeReporter func()
what's the intended use for this?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/bootstrap/peers.go
> +		if isAdded {
this boolean is not reset to false before each iteration. is that intentional? why not just check it inside the `case evt := <-sub.Out():` where isAdded is true?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/full.go
> +package lp2p
what does the filename full.go mean? why separate this from host.go?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/full.go
> +	fh.bootstrap.Stop()
do you care about error here?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/peerexchange/crawler.go
> +			go func() {
use errgroup here? it seems we can leak goroutines if the node shutdown in the middle of query

2021-10-22 11:23 UTC, countvonzero commented on lp2p/peerexchange/crawler.go
> +			// TODO(dshulyak) will be correct to call after EventHandshakeComplete is received
do you mean that when we get a result back from `Request`, we have not completed handshake?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/bootstrap/peers.go
> +	p.wg.Add(1)
use errgroup?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/handshake/handshake.go
> +			log.Uint32("peer-network-id", msg.Network))
can we log the peer IP for this network mismatch? we saw this even in devnet.

2021-10-22 11:23 UTC, countvonzero commented on lp2p/host.go
> +type Config struct {
would be nice to have the fields commented

2021-10-22 11:23 UTC, countvonzero commented on lp2p/host.go
> +		cm.Protect(addr.ID, "bootstrap")
what happened when you remove this?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/peerexchange/addrbook.go
> +	if !IsRoutable(addr.IP) && IsRoutable(src.IP) {
why do we care if src is routable or not in this case?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/peerexchange/known_address.go
> +	LastSuccess time.Time
why are the fields changed to public but the struct itself is private?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/peerexchange/crawler.go
> +			r.logger.Debug("crawl finished by timeout")
log the error? is it for sure timeout?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/peerexchange/discovery.go
> +	port, err := portFromAddress(h)
strange. this is not something we can set in the config?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/peerexchange/discovery.go
> +			port, err := portFromAddress(h)
wasn't this done already in line 64? i think i am missing something.

2021-10-22 11:23 UTC, countvonzero commented on lp2p/peerexchange/protocol.go
> +	logger := p.logger.WithFields(log.String("type", "getaddresses"),
should we log protocol instead?

2021-10-22 11:23 UTC, countvonzero commented on lp2p/peerexchange/store.go
> +	w, err := os.Create(path)
i wonder if we should create a tmp file and swap after the write is successful.

2021-10-22 12:16 UTC, dshulyak commented on lp2p/bootstrap/peers.go
> +func NewPeers(h host.Host, opts ...Opt) *Peers {
it is initialized externally

2021-10-22 12:16 UTC, dshulyak commented on lp2p/bootstrap/peers.go
> +func WithNodeStatesReporter(f func()) Opt {
it was used for to send some events, not sure if anyone was using it but i will restore it

2021-10-22 12:17 UTC, dshulyak commented on lp2p/bootstrap/bootstrap.go
> +				b.host.ConnManager().TagPeer(hs.PID, "outbound", 100)
yes

2021-10-22 12:18 UTC, dshulyak commented on lp2p/bootstrap/bootstrap.go
> +			if _, exist := peers[hs.PID]; exist {
yes, connection with the same peer is not prohibited, the likelihood of it very low, but there is no explicit mechanism to enforce single connection if two peers will try to establish connection simultaneously, or if peer will create multiple connections by intention

2021-10-22 12:18 UTC, dshulyak commented on lp2p/bootstrap/peers.go
> +	nodeReporter func()
to send some notification when node state changes

2021-10-22 12:18 UTC, dshulyak commented on lp2p/bootstrap/peers.go
> +		if isAdded {
most of this code was copied, i will double check

2021-10-22 12:20 UTC, dshulyak commented on lp2p/full.go
> +package lp2p
it is separated so that i can initialize full host by wrapping a mock host

2021-10-22 12:20 UTC, dshulyak commented on lp2p/full.go
> +	fh.bootstrap.Stop()
no

2021-10-22 12:20 UTC, dshulyak commented on lp2p/peerexchange/crawler.go
> +			go func() {
most of the code in peerexcchange is copied, there are many things that can be done differently but i dont want to do that in this pr

2021-10-22 12:21 UTC, dshulyak commented on lp2p/peerexchange/crawler.go
> +			// TODO(dshulyak) will be correct to call after EventHandshakeComplete is received
yes, so Good in this case means reachable and not necessarily good for this network

2021-10-22 12:21 UTC, dshulyak commented on lp2p/host.go
> +		cm.Protect(addr.ID, "bootstrap")
bootnode becomes prunable by connection manager

2021-10-22 12:23 UTC, dshulyak commented on lp2p/peerexchange/addrbook.go
> +	if !IsRoutable(addr.IP) && IsRoutable(src.IP) {
this enables to run peerexchange both in private and public network. e.g. if peer is routable but it sends us unroutable address we will not add it to the book. inherited from previous p2p

2021-10-22 12:23 UTC, dshulyak commented on lp2p/peerexchange/known_address.go
> +	LastSuccess time.Time
struct is not useful outside this module, but it is being marshalled

2021-10-22 12:23 UTC, dshulyak commented on lp2p/peerexchange/crawler.go
> +			r.logger.Debug("crawl finished by timeout")
yes, query exits only if context is terminated

2021-10-22 12:24 UTC, dshulyak commented on lp2p/peerexchange/discovery.go
> +	port, err := portFromAddress(h)
it is set from config (e.g. Listen option), but we need parse, also this port may change because of nat

2021-10-22 12:24 UTC, dshulyak commented on lp2p/peerexchange/discovery.go
> +			port, err := portFromAddress(h)
we listen for address update events (such as UPnP port mapping)

2021-10-22 12:25 UTC, dshulyak commented on lp2p/peerexchange/store.go
> +	w, err := os.Create(path)
that would be correct, i will open an issue after merge

2021-10-22 12:34 UTC, dshulyak commented on lp2p/bootstrap/bootstrap.go
> +			if exist && b.host.Network().Connectedness(pid) == network.NotConnected {
> why is the extra check on network.NotConnected required?

to handle unexpected order of events, e.g. second connection concurrently with disconnect. i probably need to check the opposite on another event

connect 1
connect 2
disconnect 1

> and is it possible to be disconnected with the state being Connected?

i think it becomes NotConnected when there are no connection

2021-10-22 12:36 UTC, dshulyak commented on lp2p/bootstrap/peers.go
> +		if isAdded {
isAdded should be reset, but the conditional code needs to be executed after keys are created

2021-10-23 05:09 UTC, countvonzero approved these changes
thanks for the explanations.

2021-10-23 05:09 UTC, countvonzero commented on tortoisebeacon/tortoise_beacon.go
> +			return fmt.Errorf("broadcast: %w", err)
from the application logic point of view, a single failure should not stop the tortoise beacon from working, regardless of how unlikely Publish should fail.

2021-10-23 05:09 UTC, countvonzero commented on tortoisebeacon/weakcoin/weak_coin.go
> +	if err := wc.publisher.Publish(ctx, GossipProtocol, msg); err != nil {
actually i think it may be a good practice to simply put all Publish on goroutine, since it validate synchronously.

2021-10-23 05:09 UTC, countvonzero commented on lp2p/bootstrap/bootstrap.go
> +			if exist && b.host.Network().Connectedness(pid) == network.NotConnected {
right. what happens to those connected peers that failed handshake? do we disconnect explicitly?

2021-10-23 05:09 UTC, countvonzero commented on lp2p/peerexchange/crawler.go
> +			go func() {
understood. maybe leave a TODO?

2021-10-23 05:09 UTC, countvonzero commented on lp2p/host.go
> +		cm.Protect(addr.ID, "bootstrap")
as discussed during your walk-through, i think we should not special-case bootnode

2021-10-23 05:09 UTC, countvonzero commented on lp2p/peerexchange/addrbook.go
> +	if !IsRoutable(addr.IP) && IsRoutable(src.IP) {
still don't understand the rationale. does that mean we won't allow src as one of the peers?
say there is a private network, and it has a public node acting as its only gateway to the public network, we will not connect to it?

just want to understand. i understand its old code.

2021-10-25 03:15 UTC, dshulyak commented on lp2p/bootstrap/bootstrap.go
> +			if exist && b.host.Network().Connectedness(pid) == network.NotConnected {
yes, we disconnect in handshake.go

2021-10-25 03:15 UTC, dshulyak commented on lp2p/full.go
> +package lp2p
i think i will change this to Upgrade, looks to me better then Wrap

2021-10-25 03:15 UTC, dshulyak commented on lp2p/host.go
> +		cm.Protect(addr.ID, "bootstrap")
yes, i plan to double check if it can affect anything and remove it soon after merge

2021-10-25 03:15 UTC, dshulyak commented on lp2p/peerexchange/addrbook.go
> +	if !IsRoutable(addr.IP) && IsRoutable(src.IP) {
src is the address of the peer that sends us the addr.
we ignore any info about peers connected over the private network when our host is connected over the public network with src peer.

the rationale is that we don't want to propagate private addresses as it will pollute whole network with unreachable nodes and slow down discovery. but we want to support them for testing, that's why this condition is applied only when we are connected over public network. we may consider specifying this condition explicitly.

> say there is a private network, and it has a public node acting as its only gateway to the public network, we will not connect to it?

it will work if every host in the private network connects to this public gateway over private subnet and gateway connects with the rest over public. but tbh i am not sure that custom topologies are important for spacemesh.

2021-10-25 05:22 UTC, dshulyak commented
bors try

2021-10-25 06:17 UTC, dshulyak commented
bors merge

2021-10-25 07:13 UTC, closed without merging