Refactor `mesh.go` logic into `SVM.ApplyLayer`
spacemeshos/go-spacemesh pull request #2864
Opened 2021-10-06 10:43 UTC by neysofu

## Motivation

Closes #2831. It also brings forward #2069 by replacing `big.Int` with `uint64` in a few places.

## Changes

This PR completely replaces the `mesh.go:txProcessor` API with `mesh.go:svm`, which adds the `ApplyLayer` method. Some logic is then moved into the `svm` package.

## Test Plan

Relying on the current testing infrastructure as no functional changes are expected.

## DevOps Notes
- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

2021-10-07 10:45 UTC, dshulyak commented
it came up some time ago that we can't fit balance into 64 bits - https://github.com/spacemeshos/go-spacemesh/issues/2718#issuecomment-905974522 . if that's the case we should move not to uint64, but to big.Int or uint256/128 using custom lib. can we clarify that before moving forward with a proposed refactoring?

2021-10-07 10:49 UTC, neysofu commented
@dshulyak absolutely, I was under the impression that we wanted to move forward with `uint64`, my bad! Most of this refactoring is unrelated to reward types and the work that I've done already is easily reversible. I'll put it on hold. @noamnelke I'll keep this PR focused on `SVM.ApplyLayer` and not deal with reward types.

2021-10-07 11:29 UTC, neysofu commented
I see most of the code that I'm touching is still based on `*big.Int` (`uint64` as well, but we've established already that's not okay). I'm not sure if `*big.Int` the final decision, but I guess I should conform to that for all new code. @dshulyak what do you think?

2021-10-07 13:05 UTC, dshulyak commented
> I'm not sure if *big.Int the final decision, but I guess I should conform to that for all new code. @dshulyak what do you think?

i think the same. based on the latest observations it is safer to assume that we won't be able to use uint64

2021-10-12 15:17 UTC, noamnelke commented
Added this comment: https://github.com/spacemeshos/go-spacemesh/issues/2718#issuecomment-941092617

Let's use `uint64` 😃

2021-10-13 02:14 UTC, countvonzero commented on activation/activationdb_test.go
> +func (MockSVM) ApplyLayer(layerID types.LayerID, transactions []*types.Transaction, rewards []types.AmountAndAddress) ([]*types.Transaction, error) {
nit: rm variable names

2021-10-13 02:14 UTC, countvonzero commented on mesh/mesh.go
> +	Blocks      []types.AmountAndAddress
why is it named Blocks?

2021-10-13 02:14 UTC, countvonzero commented on common/types/transaction.go
> +// AmountAndAddress stores an amount together with an account's address.
maybe RewardInfo, RewardRecipient?
naming a struct by its contents may not be future-proof :)

2021-10-13 02:14 UTC, countvonzero commented on mesh/mesh.go
> +	BySmesher   map[string][]int
what is this map storing?

2021-10-13 02:14 UTC, countvonzero commented on mesh/mesh.go
> +	for smesherString, idxs := range lr.BySmesher {
i am not sure. but it seems that data inside BySmesher and Blocks can be combined somehow to make this code more intuitive? i.e. loop over the coinbase instead of smesher+block-lookups

2021-10-13 02:14 UTC, countvonzero commented on mesh/mesh.go
> +	LayerReward uint64
what is the diff btwn TotalReward and LayerReward

2021-10-13 02:14 UTC, countvonzero commented on mesh/mesh.go
> +func (msh *Mesh) reportRewards(lr layerRewards) {
perhaps use *types.layerRewards here and below to save copying struct. normally i wouldn't care for small/simple struct but here there are 3 copies made for log/report/write.

2021-10-13 02:14 UTC, countvonzero commented on mesh/mesh.go
> +func (msh *Mesh) writeRewards(lr layerRewards) error {
any chance report and write can be combined? they seem to do the same loop, just slightly different output

2021-10-13 02:14 UTC, countvonzero commented on mesh/mesh.go
> +	fmt.Printf("CALLING APPLYSTATE with %d valid txs, layer %d \n", len(validBlockTxs), l.Index().Value)
rm or log?

2021-10-13 02:14 UTC, countvonzero commented on svm/api.go
> +func (svm *SVM) ApplyLayer(layerID types.LayerID, transactions []*types.Transaction, rewards []types.AmountAndAddress) (failed []*types.Transaction, err error) {
can we avoid using named returned variables? i have seen too many subtle bugs like assignment by accident.

2021-10-19 10:50 UTC, neysofu commented on mesh/mesh.go
> +	fmt.Printf("CALLING APPLYSTATE with %d valid txs, layer %d \n", len(validBlockTxs), l.Index().Value)
Removed. This slipped through, it was never intended to make upstream.

2021-10-19 10:51 UTC, neysofu commented on mesh/mesh.go
> +	LayerReward uint64
`Total` is `LayerReward` plus layer fees. I've removed `Total` and turned it into a method which calculates it on the fly.

2021-10-19 10:53 UTC, neysofu commented on mesh/mesh.go
> +	BySmesher   map[string][]int
It was supposed to indexes into `Blocks`, but it was ugly as hell and confusing. I think it's better now.

2021-10-20 09:27 UTC, noamnelke requested changes

2021-10-20 09:27 UTC, noamnelke commented on mesh/mesh.go
> +type svm interface {
Not sure the interface should be called `svm`. We should call it something based on the role of this object in the local context - possibly `state`. `state.ApplyLayer()` makes sense, all the other functions, too. SVM is just an implementation of the state component.

2021-10-20 09:27 UTC, noamnelke commented on svm/api.go
> +	*state.TransactionProcessor
I think this is a bad idea. The purpose of creating the `SVM` struct is to gain precise control over the methods it exposes. I think that this is a bad shortcut that will make the next phases of the SVM transition harder.

With this change, `SVM` exposes the same api as `TransactionProcessor` allowing us to use it in its place and making it harder to see what methods we still need to either implement in `SVM` or eliminate.

If there are methods that need to eventually be implemented in `SVM` - let's create them and call the matching method in `TransactionProcessor` explicitly. If there are methods that **don't** need to be there eventually, but handling them properly is unrelated to this PR - you can give them the same treatment, but add a `TODO` to remove them.

2021-10-20 09:27 UTC, noamnelke commented on mesh/mesh.go
> +type svm interface {
Also, most of the methods here make sense to be implemented in the `SVM`, with one exception: `ValidateAndAddTxToPool`. Does the transaction processor currently have access to the mempool? I think we should separate it, but not in this PR - for now you can implement this method - but add a `TODO` to remove it.

2021-10-20 09:34 UTC, neysofu commented on svm/api.go
> +	*state.TransactionProcessor
Ok, so to recap:

- `SVM` is not a good name for the interface. I understand your point, which makes sense. We can use `state` rather than the old `txProcessor`, I think that's okay.
- Exposing `SVM.TransactionProcessor` is simply a step towards full integration. This way, most of the code stays the same - because all previously used methods are also available on `SVM`. This was a plus in my book - incremental changes moving the abstraction layer from `txProcessor` to `SVM`, but of course the downside is that indeed you can lose track of where we are in the integration refactoring process.

2021-10-20 09:36 UTC, neysofu commented on svm/api.go
> +	*state.TransactionProcessor
I'll undo this change and implement all methods on `SVM` directly, which will then call into `TransactionProcessor`. In a future PR, we can decide which methods to keep and which ones to discard; I'll make sure to leave a `TODO` note to help us remember. Sounds good?

2021-10-25 08:38 UTC, countvonzero commented on mesh/mesh.go
> +			msh.With().Info("skipping reward distribution for block with no atx", bl.LayerIndex, bl.ID())
how is this possible?

2021-10-25 08:38 UTC, countvonzero commented on mesh/mesh.go
> +			msh.With().Warning("atx from block not found in db", log.Err(err), bl.ID(), bl.ATXID)
i think this should be error. these blocks have been previously verified

2021-10-25 08:38 UTC, countvonzero commented on mesh/mesh.go
> +		msh.With().Info("no valid blocks for layer", l.Index())
is this log message correct? these are all valid blocks...

2021-10-25 08:38 UTC, countvonzero commented on mesh/mesh.go
> +		msh.With().Info("no valid blocks for layer", l.Index())
also, is this an error? is it possible that there is no coinbase for a layer?

2021-10-25 08:38 UTC, countvonzero commented on mesh/mesh.go
> +		coinbases = append(coinbases, atx.Coinbase)
this list may contain duplicate elements. is that expected by the consumers?

2021-10-25 08:58 UTC, neysofu commented on mesh/mesh.go
> +			msh.With().Info("skipping reward distribution for block with no atx", bl.LayerIndex, bl.ID())
This whole portion was left untouched by the current PR. Maybe we can investigate in the future in a follow-up PR? I'm not really familiar with this code.

2021-10-25 09:00 UTC, neysofu commented on mesh/mesh.go
> +			msh.With().Warning("atx from block not found in db", log.Err(err), bl.ID(), bl.ATXID)
Same as above, this is not super relevant but I think it should be addressed in a separate PR.

2021-10-25 09:05 UTC, neysofu commented on mesh/mesh.go
> +		msh.With().Info("no valid blocks for layer", l.Index())
Unsure; I left this untouched. I believe some tests were failing without custom handling in this `else` block (triggers division by zero). We can easily remove this if it proves not to be necessary.

2021-10-25 09:06 UTC, neysofu commented on mesh/mesh.go
> +		msh.With().Info("no valid blocks for layer", l.Index())
The log message is inside the `else` block, which deals with the situation where there are no (valid) blocks at all. I believe it's correct, am I missing something?

2021-10-25 09:08 UTC, neysofu commented on mesh/mesh.go
> +		coinbases = append(coinbases, atx.Coinbase)
I think it is, it definitely is for all reward calculation logic and `state` code. It's expected that a miner can submit more than one block per layer.

2021-10-25 10:25 UTC, noamnelke approved these changes
I think it looks good to merge. There's obviously lot's of follow up work. Will you create issues for everything and mention them in the epic?

2021-10-25 10:54 UTC, neysofu commented
On it!

2021-10-25 10:58 UTC, neysofu commented
bors try

2021-10-25 11:06 UTC, neysofu commented
bors merge

2021-10-25 12:05 UTC, closed without merging