[Merged by Bors] - hare: determine good blocks based on beacon value
spacemeshos/go-spacemesh pull request #2868
Opened 2021-10-07 04:32 UTC by countvonzero

## Motivation

Closes #2811
also follow up on beacon sync PR https://github.com/spacemeshos/go-spacemesh/pull/2850, add test to hare

## Changes

- add test to hare.onTick for not synced and beacon unavailable
- use gomock for mockRoracle
- use epoch beacon value to decide good blocks as the hare's proposal set

## Test Plan

unit tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

2021-10-08 15:07 UTC, dshulyak commented
@countvonzero does this change effectively enables tortoise beacon? i think it is definitely in a better shape now, but if there are still some issues with reliability it can easily halt the whole network. we need to test it maybe with chaos mesh before pushing it to next devnet

2021-10-08 22:23 UTC, countvonzero commented
> @countvonzero does this change effectively enables tortoise beacon? i think it is definitely in a better shape now, but if there are still some issues with reliability it can easily halt the whole network. we need to test it maybe with chaos mesh before pushing it to next devnet

yes, it effectively enables tortoise beacon.

i am not familiar with "test it with chaos mesh". is that a special setup?
my assumption was that it will be tested like the current devnet, running a while with late nodes joining before releasing to the public. and any problems observed we fix them right away.

@moshababo FYI

2021-10-09 04:02 UTC, dshulyak commented
> i am not familiar with "test it with chaos mesh". is that a special setup?

it can be used to create various conditions for nodes in the network - https://chaos-mesh.org/

> my assumption was that it will be tested like the current devnet, running a while with late nodes joining before releasing to the public. and any problems observed we fix them right away.

that test by itself is not sufficient to find non-basic issues with joiners. i think that in general, we should plan for advanced testing before merging critical changes, but up to you

2021-10-09 04:32 UTC, countvonzero commented
> it can be used to create various conditions for nodes in the network - https://chaos-mesh.org/
>
> > my assumption was that it will be tested like the current devnet, running a while with late nodes joining before releasing to the public. and any problems observed we fix them right away.
> 
> that test by itself is not sufficient to find non-basic issues with joiners. i think that in general, we should plan for advanced testing before merging critical changes, but up to you

thanks for the info @dshulyak this is a great idea. 

specifically for this PR, my thoughts are:
- while i strongly support adding chaos mesh testing to go-spacemesh, it looks like it requires dedicated resource to set up for our nodes. 
- this PR is relatively simple (most code change are adding test) and i'd like to merge it sooner rather than later as the codebase changes rather fast
- this change will expose bugs in current tortoise beacon impl, and failure in that protocol will cause the consensus to stall and cause frustration to our users

so here is my proposal:
- add metrics for different beacon values in the network (done)
- flag-gate this feature. only turn it ON for unit/system tests and OFF for devnet
- there are still a few more PRs to complete the tortosie beacon protocol (in tortoise/self-healing). we can concurrently have resource working on setting up chaos mesh while i finish the rest of the impl. at that time i can do better testing with it.

alternatively, i also feel brave/ignorant enough to run with it and debug as bugs happen :P 
but i don't bear the front of the community's reaction to a failing devnet, it's more fair for @moshababo to make the call

2021-10-09 05:31 UTC, dshulyak commented
> while i strongly support adding chaos mesh testing to go-spacemesh, it looks like it requires dedicated resource to set up for our nodes.

it is not complicated. it can be installed with a single command. i was using it to find issues in the last devnets

> alternatively, i also feel brave/ignorant enough to run with it and debug as bugs happen :P

the problem is that if there are unresolved issues they will complicate debugging for other development efforts, in particular for libp2p. i am in general don't mind debugging smaller things as we go, but for critical parts that can stall the network, it will be very frustrating.

2021-10-09 05:34 UTC, dshulyak requested changes

2021-10-09 05:34 UTC, dshulyak commented on tortoisebeacon/metrics/prometheus.go
> +		[]string{"epoch", "beacon"},
we can't use labels that grow in time, it is effectively a memory leak. similar to one that we had recently for blocks

2021-10-09 06:17 UTC, countvonzero commented on tortoisebeacon/metrics/prometheus.go
> +		[]string{"epoch", "beacon"},
hmmm.... is it possble to delete old values as we go? this should grow slowly.

or do you have other idea?
i am trying to achieve something like expvar's Map where we can see for a given epoch there are N beacons observed with count/weight.

or if is there a way to dynamically generate a counter at runtime where the counter name contains epoch and beacon value?

2021-10-09 23:25 UTC, countvonzero commented
> it is not complicated. it can be installed with a single command. i was using it to find issues in the last devnets

do you think i can try this on the system test. i.e. change the tests to run indefinitely and test the chaos scenario on those 50 nodes?

2021-10-10 11:35 UTC, dshulyak commented on tortoisebeacon/metrics/prometheus.go
> +		[]string{"epoch", "beacon"},
i think [collectors](https://github.com/prometheus/client_golang/blob/v1.11.0/prometheus/collectors/dbstats_collector.go) fits this pattern

2021-10-10 11:42 UTC, dshulyak commented
> do you think i can try this on the system test. i.e. change the tests to run indefinitely and test the chaos scenario on those 50 nodes?

should work (i think it is simpler with spacecraft though). maybe disconnecting some fraction of nodes periodically for an extended period of time, so they go out of sync and miss tortoise beacon round, and then checking proposed metrics would be a good test

2021-10-12 07:43 UTC, countvonzero commented
bors try

2021-10-12 09:50 UTC, countvonzero commented
bors try

2021-10-13 03:11 UTC, dshulyak approved these changes

2021-10-13 03:11 UTC, dshulyak commented on tortoisebeacon/metrics/prometheus.go
> +	"github.com/prometheus/client_golang/prometheus"
it is a bit weird that we are using go-kit everywhere else and prometheus metrics directly here. i don't mind using prometheus library directly, but consistency would be nice

2021-10-13 03:42 UTC, countvonzero commented on tortoisebeacon/metrics/prometheus.go
> +	"github.com/prometheus/client_golang/prometheus"
yes. tho go-kit metrics doesn't expose the Exporter/Collector functionality. in the long run it seems easier to use prometheus directly. i'll file an issue for that.

2021-10-16 09:36 UTC, countvonzero commented
bors try

2021-10-16 10:32 UTC, countvonzero commented
bors try

2021-10-17 13:16 UTC, noamnelke approved these changes

2021-10-17 13:16 UTC, noamnelke commented on hare/hare.go
> +		return false, fmt.Errorf("broker registerr: %w", err)
```suggestion
		return false, fmt.Errorf("broker register: %w", err)
```

2021-10-17 13:16 UTC, noamnelke commented on hare/hare.go
> +					h.WithContext(ctx).With().Warning("consensus not started for layer", layer)
Why not return this as an error? Seems like we're handling the error and non-error case the same way, so why return an extra boolean?

2021-10-18 03:18 UTC, countvonzero commented
FYI @dshulyak @noamnelke 

here the result of more extensive testing with spacecraft+devnet config (50 nodes)
the network has 20 min epoch. beacon protocol usually takes 8 min 30 seconds

note that i was unable to run chaos-mesh. it seems the chaos-mesh tools couldn't find the runtime container binary. i ended up doing `kubectl get pods -n default --no-headers=true | awk '/miner-4/{print $1}' | xargs kubectl delete pods` to take out 11 pods at a time.

### taking 11 nodes out at the beginning/middle/near the end of tortoise beacon protocol
the network was able to consistently produce the beacon values, and those out-of-sync nodes were able to sync the beacon value via blocks. here's some data
- 50 nodes entered beacon protocol, 39 completed
- in the following rounds 42 nodes enter the protocol, and 42 completed
- took 2 epochs for the network to recover with all 50 nodes participating in the beacon protocol

### taking 22 nodes out at the beginning/middle/near the end of tortoise beacon protocol
very similar to the 11 nodes experiment. 
- 50 nodes entered beacon protocol, 22 completed
- in the following rounds 41 nodes enter the protocol, and 41 completed
- took 4 epochs for the network to recover with all 50 nodes participating in the beacon protocol

### taking 11 nodes out every 2 minutes during the tortoise beacon protocol, total 33 pods got restarted
the network did not recover from this experiment due to sync+hare issues. the network's processed layer stuck at 348.
1 node was able to enter into gossip sync. 32 nodes were not able to sync because none of its peers have processed layer higher than 348. hare produced empty set (`terminating: reached iterations limit`) up to layer 372.

however, the beacon protocol continues to run with the remaining 17 nodes that are still synced. here is the output of each epoch. below is the query result from prometheus `group by(epoch,beacon) (spacemesh_beacons_beacon_calculated_weight)` and `group by(epoch,beacon) (spacemesh_beacons_beacon_observed_total)`


| beacon | epoch |
| ------------- | ------------- |
| aeebad4a79 | 1 |
| aeebad4a79 | 2 |
| 2550f7d0de | 3 |
| 1cc281a72b | 4 |
| 638ec2dd16 | 5 |
| 801398e571 | 6 |
| e4201e7da1 | 7 |
| 29149f6c0a | 8 |
| 3aaecd76da | 9 |
| 170c280455 | 10 |
| 1c1f24fcb8 | 11 |
| 6bda060b4b | 12 |
| cc56e9680f | 13 |
| 9a0bacf88e | 14 |
| 845027bb55 | 15 |
| db235dd4bc | 16 |
| f3562f08ed | 17 |
| 856d7c79b5 | 18 |
| 186ac50f62 | 19 |
| 3da3937d38 | 20 |
| 0a45b1a456 | 21 |
| 075ad1dec4 | 22 |
| e2ab8d2aa9 | 23 |
| 241427139e | 24 |
| 706ac187a9 | 25 |
| c25cef83f7 | 26 |
| a3f6960836 | 27 |
| 1cfe36f972 | 28 |
| bbebce088f | 29 |
| 49ecdfdba0 | 30 |
| acc7809206 | 31 |
| dc1773e02c | 32 |
| 6aac891b53 | 33 |
| f2e42375da | 34 |
| 93f85502f4 | 35 |
| 9ab166183d | 36 |
| 7409e4f848 | 37 |
| 81233bfc96 | 38 |
| d30ba3be9f | 39 |
| 5883d8d668 | 40 |
| c3002d18a8 | 41 |
| 776889d848 | 42 |
| 7f0d138720 | 43 |
| 03cd7bc927 | 44 |
| df0a21aee4 | 45 |
| 76c2196efb | 46 |
| ac65753bad | 47 |
| cb895cb1a3 | 48 |
| 93f7775a27 | 49 |
| 9e4bf683c1 | 50 |
| b8760e36e3 | 51 |
| f63d437fbd | 52 |
| 947594119e | 53 |
| 69a6390bba | 54 |
| c36b90d1aa | 55 |
| 8aa5676026 | 56 |
| 0465d69b61 | 57 |
| 7a845f26f5 | 58 |
| 55ce829d99 | 59 |
| cca8250981 | 60 |
| 8385d30ff7 | 61 |
| dbedfe23f4 | 62 |
| 0daf714a7e | 63 |
| 5e1d436d10 | 64 |
| 01a4a425d7 | 65 |
| e613be85b8 | 66 |
| 7e7698e36a | 67 |
| 83a8827734 | 68 |
| b901ec1356 | 69 |
| e21661fd56 | 70 |
| 6d1370ea64 | 71 |
| 4129555c90 | 72 |
| 5a522eb873 | 73 |
| 8c639223c2 | 74 |
| 744e740af1 | 75 |
| 7aa071a7d2 | 76 |
| ef086080b5 | 77 |
| d05f5da1b8 | 78 |
| 2c89763dab | 79 |
| 99fe5b774b | 80 |
| f90fb46b4c | 81 |
| 651b0e7ec7 | 82 |
| 370e105cd7 | 83 |
| 0eeef9cb6f | 84 |
| 3138da63f2 | 85 |
| 6d5a2850c8 | 86 |
| afd4010d85 | 87 |
| 6e8ba1f8b2 | 88 |
| e32dab4b7e | 89 |
| 90df90bc73 | 90 |
| 34bfc07523 | 91 |
| f0eee015e7 | 92 |
| f6a2d482f3 | 93 |
| c86f94a570 | 94 |
| f86e3e88db | 95 |
| e627a00772 | 96 |
| 6215a2c845 | 97 |
| c7cf62bc9f | 98 |
| b6e63df560 | 99 |
| 38f1d6d8e2 | 100 |
| 8bfa23f38e | 101 |
| 84470f6bff | 102 |
| 91a9e5c4ec | 103 |
| ecfecc9660 | 104 |
| e912ef790d | 105 |
| 788b8aebd0 | 106 |
| e446942efa | 107 |
| 8965acb16a | 108 |
| e7e4aa2967 | 109 |
| 8fe51571f8 | 110 |

2021-10-18 03:29 UTC, countvonzero commented on hare/hare.go
> +					h.WithContext(ctx).With().Warning("consensus not started for layer", layer)
this is purely for testing and debugging.
it's easier to test individual calls to `onTick` instead of starting `tickerLoop`. and there are legit situations where we don't return an error but didn't participate in the protocol.
- genesis
- node shutting down
- **new behavior and hence needs testing**: node has not collected enough beacon values to participate in the protocol yet.

2021-10-18 10:01 UTC, countvonzero commented
bors merge

2021-10-18 10:57 UTC, closed without merging