Add a test that measures memory consumption of malformed proposal decoding
spacemeshos/go-spacemesh pull request #3018
Opened 2021-12-22 18:42 UTC by nkryuchkov

## Motivation

Closes #3014 

The added test shows that https://github.com/nullstyle/go-xdr/xdr3 consumes 3 GB when trying to decode a malformed proposal with 3 KB length:
```
=== RUN   Test_decodeMalformedProposal
    proposal_test.go:101: Total cumulative alloc: 267K
    proposal_test.go:101: Total cumulative alloc: 3G
--- PASS: Test_decodeMalformedProposal (0.05s)
PASS
```

## Changes

- Add a test that measures memory consumption of malformed proposal decoding

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

2021-12-22 23:58 UTC, countvonzero approved these changes
thanks!!!

i am curious. is this specific to Proposal? or does any malformed data cause such crazy mem consumption with xdr?

2021-12-23 04:01 UTC, dshulyak requested changes
good repro, but i don't think that we need to commit a test that causes memory to grow so much.
beside that this is clearly a bug in xdr3 that makes whole network vulnerable to a trivial ddos

technically it is not even a test, it is just an example, i don't see any reason to have it in the repo. if it is needed to keep the repro script around you can leave a link in the issue

2021-12-23 08:19 UTC, nkryuchkov commented
@countvonzero 

Not any malformed data causes such consumption. There're malformed proposals that consume just a few KBs of memory:
```
=== RUN   Test_decodeMalformedProposal1
    proposal_test.go:128: Total cumulative alloc: 265.5K
    proposal_test.go:128: Total cumulative alloc: 272.9K
--- PASS: Test_decodeMalformedProposal1 (0.00s)
PASS
```

But also there're ones that consume even more than in the description:
```
=== RUN   Test_decodeMalformedProposal2
    proposal_test.go:128: Total cumulative alloc: 268.5K
    proposal_test.go:128: Total cumulative alloc: 28.1G
--- PASS: Test_decodeMalformedProposal2 (0.64s)
PASS
```

I think it's specific to a data pattern and may be reproduced with other data structures.

2021-12-23 08:21 UTC, nkryuchkov commented
@dshulyak I agree, we don't need this in the repo. It's more like a PoC that I wanted to show

2021-12-23 09:03 UTC, closed without merging