2703 hash not found
spacemeshos/go-spacemesh pull request #3218
Opened 2022-05-20 12:06 UTC by evt

## Motivation
Closes #2703 

## Changes

## Test Plan

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

2022-05-20 14:08 UTC, countvonzero requested changes
this is the intuitive approach for the issue indeed. but as commented below we should try harder to dish out the work evenly. note that your PR only affect syncing block/ballot. synced txs and gossiped block/ballot/txs are not handled.

i wonder if we should solve this problem from a different angle. if we create a fixed-size FIFO cache of hash->set of peer, then we can solve this more generally (without adding peer to all the APIs)

for example, in the syncing case.
when receiving layer data from peers A, B, C. we came compile a mapping that 
ballot_X_hash: A, B
ballot_Y_hash: A, B, C
ballot_Z_hash: C
so when it comes time to fetch ballot XYZ, we look up from the map and choose a random one in its peer list.

if a hash doesn't exist in the mapping, we just choose a random peer.

also, block can be fetched as a result of data integrity check when handling a ballot. say ballot_X contains votes for block_G. in this case when we ask to fetch block_G_hash, we could optionally provide a referral hash ballot_X_hash and from the mapping we know we can ask peer A or B for block_G_hash because if they don't have it, then they are giving us incomplete data and therefore malicious.

2022-05-20 14:08 UTC, countvonzero commented on fetch/fetch.go
> +	id := randSeq(10)
what is this used for? how is this different from batch.ID?
if you want it for cross-requestst tracing, use a context with the same request ID

2022-05-20 14:08 UTC, countvonzero commented on fetch/fetch.go
> +			oldPear := peer
oldPeer

2022-05-20 14:08 UTC, countvonzero commented on fetch/fetch.go
> +		if p2p.IsAnyPeer(peer) {
this should be outside the loop. it can only be empty when it enter this method.

2022-05-20 14:08 UTC, countvonzero commented on fetch/fetch.go
> +		// if we've tried peer already - try to change (just once to avoid infinite loop if only 1 peer available)
don't think this logic is necessary.

say we have retries == 100. but we only have 9 peers. this logic will effectively reduce the retries to 9.
a peer may not have a hash at t0, but it may have the hash at t1.

2022-05-20 14:08 UTC, countvonzero commented on layerfetcher/layers.go
> +		if err := l.fetchLayerData(ctx, logger, peer, layerID, peerRes.data); err != nil {
i think i commented about this before in slack.
say we have 3 peers ABC. the peers return layer data in the following time sequence CAB. and they gave us exactly the same layer data. 
before this PR, all hashes will be distributed evenly between A, B and C.
after this PR, block/ballot hashes will all go to peer C.

i don't think this is a good behavioral change. 
we can wait until all peers reported back and evenly distribute the work amongst them in fetchLayerData

2022-05-20 14:10 UTC, evt commented on fetch/fetch.go
> +	id := randSeq(10)
this is just for debugging purposes to see log messages for the same `sendBatch` call. I have now a case where peer is attached to request (and thus should have data we need), but somehow has is still not found, so debugging to find out why.

2022-06-07 12:17 UTC, evt commented
Closed in favour of https://github.com/spacemeshos/go-spacemesh/pull/3244

2022-06-07 12:17 UTC, closed without merging