Add pre-commit git hook
spacemeshos/go-spacemesh pull request #4147
Opened 2023-03-13 10:14 UTC by piersy

## Motivation

I found this pre-commit hook useful, it saved me from waiting for needless CI runs. It's not exhaustive, but it only takes a few seconds on my machine.

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

2023-03-13 12:28 UTC, dshulyak requested changes, later dismissed
i would prefer if this was made optional.
i am making commits very frequently when working on something non-trivial, waiting couple of seconds doen't seem good

2023-03-13 15:09 UTC, piersy commented
@dshulyak It is optional, to enable the hook you would need to symlink to the added file in the `.git/hooks` directory.  I.e. run `ln -s ../../githooks/pre-commit` from inside `.git/hooks`

2023-03-13 16:52 UTC, countvonzero commented
> @dshulyak It is optional, to enable the hook you would need to symlink to the added file in the `.git/hooks` directory. I.e. run `ln -s ../../githooks/pre-commit` from inside `.git/hooks`

hmmm.... don't you then need to add .git/hooks to the ignored files? why not simply do that and you can do whatever in .git/hooks?

2023-03-14 10:06 UTC, fasmat commented
@countvonzero the `.git/hooks` directory is not added to the index by default.

I'm not a huge fan of hooks running part of the CI locally, it makes working with git much slower. I feel like `make test-fmt` or `make test-tidy` can become quit annoying on every commit, since I like to amend and rebase commits before I push them and these checks would interfere with my workflow 🙁 .

Since the hook is currently not enforced, I don't mind adding it. But at least it should then be mentioned in the `README.md`.

2023-03-14 10:12 UTC, pigmej commented
Few cents from my side, most of the IDEs or even editors have the possibility to run hooks on save / modify / focus out etc. I don't think adding such to pre-commit is that valuable nowadays, honestly.

2023-03-14 12:46 UTC, piersy commented
@pigmej yes you can do this just locally through your IDE, but I thought it could be useful for people to just have the hook pre-defined. Otherwise it takes some time to figure out what would be a good hook. It's also useful for people who are using the hook to have it managed with the repository.

That said it sounds like no-one else who has looked at this PR is going to find this useful, so I'm closing it.

2023-03-14 12:46 UTC, closed without merging