generate block right away in the non-optimistic case
spacemeshos/go-spacemesh pull request #4496
Opened 2023-06-08 06:35 UTC by countvonzero

## Motivation
Closes #4482

## Changes
- when optimistic filtering is OFF, generate a block right away regardless of layer order
- when hare output empty block, or a non-optimistic generated block, certify the hare output right away

note that block execution is still kept sequential

2023-06-08 07:27 UTC, countvonzero commented
bors try

2023-06-08 08:00 UTC, dshulyak commented
> note that block execution is still kept sequential

this is enforced by mesh, because results from tortoise are sequantial. maybe we can drop this elsewhere, so that it doesn't do unnecessary things?

2023-06-08 08:08 UTC, dshulyak approved these changes

2023-06-08 08:08 UTC, dshulyak commented on blocks/generator.go
> +	md, err := g.preprocess(out)
it would be easier to understand the code if preprocess was inlined

2023-06-08 08:08 UTC, dshulyak commented on blocks/generator.go
> +		if err = g.postProcess(out.Ctx, out.Layer, bi.block); err != nil {
maybe `saveAndCertify` or just `certifiy` ?

2023-06-08 10:03 UTC, countvonzero commented
> > note that block execution is still kept sequential
> 
> this is enforced by mesh, because results from tortoise are sequantial. maybe we can drop this elsewhere, so that it doesn't do unnecessary things?

there are 2 threads that could execute a block:
A. block generator (calling `ProcessLayerPerHareOutput`)
B. syncer (calling `ProcessLayer`)

in a steady state, case A will be ahead of tortoise verification results. B is just a backup in case the node get disconnected during hare consensus. the sequential execution here (in `processLayers`) only serves to ensure that blocks are executed in-situ sequentially. there is no reason to treat optimistic/non-optimistic differently here.

2023-06-08 10:23 UTC, dshulyak commented
> in a steady state, case A will be ahead of tortoise verification results.

tortoise will output that layer is not verified but there is a hare output, and it will be enough for mesh to allow execution without persisting validity. during optimistic filtering something else happens, block is executed and `applied` field is saved to database, after that mesh calls tortoise and re-checks that target block is already applied

2023-06-08 10:27 UTC, dshulyak requested changes
actually this change still has the same problem. you need to notify tortoise to vote on the block without enforcing order

2023-06-08 10:34 UTC, countvonzero commented
> actually this change still has the same problem. you need to notify tortoise to vote on the non-optimistic block before previous blocks are applied. otherwise it will be the same behavior as was seen

@dshulyak the code in this PR will call `AddBlockWithTXs()` as soon as hare terminates. that calls `trtl.OnBlock()`. i thought that is enough to make tortoise to vote on a block?

2023-06-08 10:37 UTC, dshulyak commented
> @dshulyak the code in this PR will call AddBlockWithTXs() as soon as hare terminates. that calls trtl.OnBlock(). i thought that is enough to make tortoise to vote on a block?

OnBlock will notify tortoise that full data is available locally. but tortoise will vote according to OnHareOutput

2023-06-08 10:40 UTC, countvonzero commented
> > in a steady state, case A will be ahead of tortoise verification results.
> 
> tortoise will output that layer is not verified but there is a hare output, and it will be enough for mesh to allow execution without persisting validity. during optimistic filtering something else happens, block is executed and `applied` field is saved to database, after that mesh calls tortoise and re-checks that target block is already applied

in case A the optimistic case, at the time of execution, the block is not generated yet. tortoise has no way to include it in the results. 

the workflow for optimistic case is:
hare terminate -> txs get executed -> block gets generated -> trtl.OnBlock() -> `applied` field is saved -> mesh get results from trtl and ensure state consistent.

i don't' understand what need changed here.

2023-06-08 10:45 UTC, countvonzero commented
> > @dshulyak the code in this PR will call AddBlockWithTXs() as soon as hare terminates. that calls trtl.OnBlock(). i thought that is enough to make tortoise to vote on a block?
> 
> OnBlock will notify tortoise that full data is available locally. tortoise will vote according to OnHareOutput

ok. thanks. i'll make that change.

2023-06-08 12:50 UTC, countvonzero commented
@dshulyak please take another look.
the code is changed to such that for empty block ID and non-optimistic block tortoise is notified as soon as hare terminate.

2023-06-08 12:51 UTC, countvonzero commented
bors try

2023-06-08 13:37 UTC, dshulyak approved these changes
thanks, this should vote correctly

>  === CONT  TestPartition_50_50
    logger.go:130: 2023-06-08T13:12:30.367Z	ERROR	TestPartition_50_50	test failed	***"err": "stream err from client boot-1: rpc error: code = Canceled desc = grpc: the client connection is closing"***
    partition_test.go:164: 
        	Error Trace:	/build/systest/tests/partition_test.go:164
        	            				/build/systest/tests/partition_test.go:194
        	Error:      	Received unexpected error:
        	            	stream err from client boot-1: rpc error: code = Canceled desc = grpc: the client connection is closing
        	Test:       	TestPartition_50_50

i think pods in this test were interrupted prematurely, usually there are more layers
![image](https://github.com/spacemeshos/go-spacemesh/assets/1964576/aeb52e26-bb23-4d7b-afa5-6855f37ce5ea)

2023-06-09 01:02 UTC, countvonzero commented
bors try

2023-06-09 02:36 UTC, countvonzero commented
bors try

2023-06-09 03:51 UTC, countvonzero commented
TestPartition_50_50 consistently fails at layer 22 :(
will need more debugging to understand.

2023-06-09 05:20 UTC, dshulyak commented
there might be a gap in events that are watched by a test, [tortoise](https://grafana.spacemesh.dev/explore?orgId=1&left=%7B%22datasource%22:%22loki-gke-dev%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22test-aeyj%5C%22,%20pod%3D%5C%22smesher-27-6dcc86c5b8-5rlcg%5C%22%7D%20%7C%3D%20%5C%22candidate%20layer%20is%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki-gke-dev%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221686277895236%22,%22to%22:%221686280702016%22%7D%7D) and [mesh](https://grafana.spacemesh.dev/explore?orgId=1&left=%7B%22datasource%22:%22loki-gke-dev%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22test-aeyj%5C%22,%20pod%3D%5C%22smesher-27-6dcc86c5b8-5rlcg%5C%22%7D%20%7C~%20%5C%22consensus%20results%7Cexecutor%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki-gke-dev%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221686277895236%22,%22to%22:%221686280702016%22%7D%7D) worked out correctly

maybe somehow mesh notifies about layer that are awaited by test before the actual test finishes

2023-06-10 11:42 UTC, countvonzero commented
bors try

2023-06-10 14:59 UTC, countvonzero commented
bors try

2023-06-10 15:27 UTC, countvonzero commented
> ## try
> Build failed:
> 
> * [systest-status](https://github.com/spacemeshos/go-spacemesh/actions/runs/5230550454/jobs/9444347996)

test passed. failed due to an unknown kubernetes error
```
=== CONT  TestPartition_50_50
    logger.go:130: 2023-06-10T15:23:04.083Z	INFO	TestPartition_50_50	namespace was deleted	***"namespace": "test-rpoz"***
--- PASS: TestPartition_50_50 (925.24s)
=== CONT  TestFallback
    logger.go:130: 2023-06-10T15:23:04.135Z	INFO	TestFallback	using	***"namespace": "test-qzao"***
rpc error: code = NotFound desc = an error occurred when try to find container "5c50d9e8ccbdb0e30cf118da4776fb3ac0c8a2bca52ef8ab4848ce31aeaae6dd": not foundtest_job_name=systest-7f6b952-1686409567 ./wait_for_job.sh
Waiting for job/systest-7f6b952-1686409567 to complete or fail
```

2023-06-10 15:27 UTC, countvonzero commented
bors try

2023-06-10 22:06 UTC, countvonzero commented
bors merge

2023-06-10 22:53 UTC, closed without merging