spawn a process to download atxs hinted by a server
spacemeshos/go-spacemesh pull request #5377
Opened 2023-12-19 09:42 UTC by dshulyak

2023-12-19 15:13 UTC, poszu approved these changes

2023-12-19 15:13 UTC, poszu commented on syncer/atxsync/atxsync.go
> +		if downloaded == total {
NIT, this expresses the intent more clearly
```suggestion
		if len(missing) == 0 {
```

2023-12-19 15:40 UTC, fasmat commented on node/node.go
> +					})
We are ranging over the `ch` channel which I don't think is correct, since so we can only return from this go routine directly after receiving an update (`<-ctx.Done()` is checked after receiving from `ch`). I fixed this already in this PR: https://github.com/spacemeshos/go-spacemesh/pull/5378 and the change for the incorrect ranging over the `ch` channel would incidentally also fix the linting issue here. 🙂

2023-12-19 15:40 UTC, fasmat commented on syncer/syncer.go
> +	}
What impact does this have on things like `<-RegisterForATXSync()`?

2023-12-19 15:40 UTC, fasmat commented on syncer/atxsync/atxsync_test.go
> +}
Would `types.BytesToATXID` also work?

2023-12-19 15:40 UTC, fasmat commented on syncer/atxsync/atxsync_test.go
> +				{request: []types.ATXID{id(3)}, result: []*types.VerifiedActivationTx{atx(id(3))}},
I think the fetcher always returns an error when it isn't able to download every ATX that it is requested to download.

2023-12-19 15:40 UTC, fasmat commented on syncer/atxsync/atxsync.go
> +		}
Besides logging I don't think filtering for missing ATXs is necessary; the fetcher already only fetches ATXs it doesn't yet have in the DB.

2023-12-19 17:49 UTC, dshulyak commented on syncer/atxsync/atxsync.go
> +		}
yes it is not necessary, i added that for logging

2023-12-19 20:09 UTC, fasmat commented on node/node.go
> +					})
The error returned from `atxsync.Download` should maybe also not be returned in the `eg.Go` function or no new go routines can be added to the group, but I believe the node will continue to run. Instead I think:

```suggestion
					app.eg.Go(func() error {
						if err := atxsync.Download(
							ctx,
							10*time.Second,
							app.addLogger(SyncLogger, app.log).Zap(),
							app.db,
							app.fetcher,
							update.Data.ActiveSet,
						); err != nil {
							app.errCh <- err
							return nil
						}
					})
```

might be correct if the node should shut down upon failing to get the ATXs from the active set.

2023-12-20 20:43 UTC, fasmat commented on syncer/syncer.go
> +	DisableAtxSync           bool   `mapstructure:"disable-atx-sync"`
Should this also be to be set via CLI?

2023-12-20 20:44 UTC, fasmat requested changes
There still is the question of will disabling sync break `RegisterForATXSync()`? Because If it does many parts of the node won't work correctly with the `DisableAtxSync` config parameter set to `true`.

2023-12-21 07:51 UTC, dshulyak commented
> There still is the question of will disabling sync break RegisterForATXSync()? Because If it does many parts of the node won't work correctly with the DisableAtxSync config parameter set to true.

it doesn't break that

2023-12-21 08:12 UTC, dshulyak commented on node/node.go
> +					})
i fixed second comment, will leave 1st for your pr

2023-12-21 08:16 UTC, dshulyak commented on syncer/syncer.go
> +	}
i renamed DisableAtxSync to DisableAtxReconciliation to make it obvious that atx downloading still works. what i disabled is additional atx sync queries at the end of the epoch

2023-12-21 08:18 UTC, dshulyak commented on syncer/syncer.go
> +	DisableAtxSync           bool   `mapstructure:"disable-atx-sync"`
i would rather leave it only for config

2023-12-21 09:24 UTC, fasmat approved these changes

2023-12-21 09:27 UTC, dshulyak commented
bors merge

2023-12-21 10:13 UTC, fasmat commented
bors merge

2023-12-21 10:37 UTC, fasmat commented
system tests were canceled early?

bors merge

2023-12-21 11:26 UTC, closed without merging