Bump post to v0.12.1 and post-rs to v0.7.1
spacemeshos/go-spacemesh pull request #5635
Opened 2024-03-01 13:40 UTC by poszu

## Motivation

Bump post dependencies to their newest versions

## Description

## Test Plan

n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

2024-03-01 17:00 UTC, fasmat approved these changes

2024-03-01 17:01 UTC, fasmat requested changes
There seems to be issues with the TLS setup in the new version of the post service?

2024-03-04 12:45 UTC, poszu commented
> There seems to be issues with the TLS setup in the new version of the post service?

Fixed key generation in the test. The TYPE field in PEM had the wrong value ("PRIVATE KEY" vs "RSA PRIVATE KEY" for PKCS1). See https://pkg.go.dev/crypto/x509#MarshalPKCS1PrivateKey

2024-03-04 12:59 UTC, fasmat approved these changes

2024-03-04 13:39 UTC, poszu commented
bors merge

2024-03-04 14:31 UTC, closed without merging