api: v2alpha1 account service
spacemeshos/go-spacemesh pull request #5982
Opened 2024-05-24 12:10 UTC by kacpersaw

```
service AccountService {
  rpc List(AccountRequest) returns (AccountList);
}
```

2024-05-28 11:41 UTC, poszu requested changes

2024-05-28 11:41 UTC, poszu commented on sql/accounts/accounts.go
> +			return true
```suggestion
			return fn(&account)
```

How about adding a UT to see if iteration is stopped when `fn` returns false?

2024-05-28 13:04 UTC, poszu approved these changes

2024-05-28 14:26 UTC, kacpersaw commented
bors merge

2024-05-28 14:57 UTC, kacpersaw commented
bors merge

2024-05-29 05:40 UTC, kacpersaw commented
bors merge

2024-05-29 06:27 UTC, closed without merging