Download athena dependencies
spacemeshos/go-spacemesh pull request #6180
Opened 2024-07-26 00:57 UTC by lrettig

## Motivation

## Description

## Test Plan

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

2024-10-04 20:36 UTC, lrettig commented
closing in favor of #6375 and the new branch

2024-10-07 11:03 UTC, poszu requested changes

2024-10-07 11:03 UTC, poszu commented on vm/templates/script/src/bin/execute.rs
> +//! Test harness for the Wallet program.
I think we don't need `script` crate with the test harness. We can test the `program` crate using integration tests located under `program/tests` (they would run the program in a VM), wdyt?

2024-10-07 11:03 UTC, poszu commented on vm/templates/common/Cargo.toml
> +parity-scale-codec = { version = "3.6.12", features = ["derive"] }
How about moving `common` and `program` into the `vm/templates/wallet/` directory?

2024-10-07 11:03 UTC, poszu commented on api/grpcserver/grpcserver_test.go
> +	vmsdk "github.com/spacemeshos/go-spacemesh/vm"
The `vm` is imported twice
```suggestion
	"github.com/spacemeshos/go-spacemesh/vm"
```

2024-10-07 11:03 UTC, poszu commented on api/grpcserver/grpcserver_test.go
> +	svm := vm.New(statesql.InMemory(), vmsdk.WithLogger(lg))
Then revert here and in all the other places:
```suggestion
	svm := vm.New(statesql.InMemory(), vm.WithLogger(lg))
```

2024-10-07 11:03 UTC, poszu commented on api/grpcserver/v2alpha1/account_test.go
> +	// "github.com/spacemeshos/go-spacemesh/vm/templates/multisig"
```suggestion
```

2024-10-07 11:03 UTC, poszu commented on api/grpcserver/v2alpha1/account_test.go
> +		// }
```suggestion
```

2024-10-07 11:03 UTC, poszu commented on api/grpcserver/v2alpha1/transaction.go
> +	// "github.com/spacemeshos/go-spacemesh/vm/templates/vesting"
Could you please clean up the commented-out parts? IMHO, there is no need to keep dead code.
```suggestion
```

2024-10-07 11:03 UTC, poszu commented on sql/accounts/accounts.go
> +			codec.DecodeFrom(stmt.ColumnReader(5), &account.Storage)
I think it's fine to panic if decoding fails as it means that the DB content is broken (it's an unrecoverable condition).
```suggestion
			_, err := codec.DecodeFrom(stmt.ColumnReader(5), &account.Storage)
			if err != nil {
				panic(fmt.Sprintf("decoding account storage: %v, err")
			}
```

2024-10-07 11:03 UTC, poszu commented on sql/accounts/accounts.go
> +				codec.DecodeFrom(stmt.ColumnReader(6), &account.Storage)
```suggestion
				_, err := codec.DecodeFrom(stmt.ColumnReader(6), &account.Storage)
				if err != nil {
					panic(fmt.Sprintf("decoding account storage: %v, err")
				}
```

2024-10-07 11:03 UTC, poszu commented on sql/accounts/accounts.go
> +				codec.DecodeFrom(stmt.ColumnReader(6), &account.Storage)
```suggestion
				_, err := codec.DecodeFrom(stmt.ColumnReader(6), &account.Storage)
				if err != nil {
					panic(fmt.Sprintf("decoding account storage: %v, err")
				}
```

2024-10-07 11:03 UTC, poszu commented on common/types/account_storage.go
> +// go:generate doesn't generate these automatically, probably because it's a slice type.
Is there a reason to have `StorageItems` in the `Account struct` instead of `[]StorageItem`? The hand-written encode/decode methods wouldn't be needed. `Storage []StorageItem` in `Account` could be initialized from the DB column as follows:

```go
var err error
account.Storage, err = codec.DecodeSliceFromReader[types.StorageItem](stmt.ColumnReader(5))
if err != nil {
	panic(fmt.Sprintf("decoding account storage: %v, err")
}
```

2024-10-07 21:28 UTC, lrettig commented on vm/templates/script/src/bin/execute.rs
> +//! Test harness for the Wallet program.
Right, this was copied over from the Athena side, right? It belongs there, not here

2024-10-07 21:30 UTC, lrettig commented on vm/templates/common/Cargo.toml
> +parity-scale-codec = { version = "3.6.12", features = ["derive"] }
"program" should probably become "wallet" (right? it's the wallet template), but there's currently another folder with that name. Let's sort out the existing Go code a little better before re-arranging these.

2024-10-07 23:35 UTC, lrettig commented
Questions:
- where do we want to compute the principal, in athena or in go-sm?
- does the nonce live inside the athena tx payload or outside? (this was brought up before but we didn't reach a final answer: https://community.spacemesh.io/t/proposed-athena-design/433#questions-14)
- where do we do gas computations, in athena or in go-sm? Assuming in athena, then we need an interface that, given a TX payload and target address + method, calculates the max gas.
- where/how do we handle encoding of the athena tx payload? (These are the parts labeled `ENCODE(...)` in [this post](https://community.spacemesh.io/t/proposed-athena-design/433#type-2-wallet-call-5).) Assuming we want this logic to live entirely inside athena, we need an interface for this, too.

2024-10-08 20:24 UTC, lrettig commented
Closing in favor of #6379

2024-10-08 20:24 UTC, closed without merging