Add debug log to v2alpha1 SubmitTransaction method
spacemeshos/go-spacemesh pull request #6449
Opened 2024-11-12 15:16 UTC by kacpersaw

## Description

Add a debug log with the transaction ID after submitting the transaction.

2024-11-12 15:43 UTC, pigmej commented
We need different way to debug that. We cannot enable globally `debug` as that will enable all debug logs, isn't it?

2024-11-12 15:48 UTC, jellonek commented
We can configure specific logger for grpc service as stated in https://github.com/spacemeshos/go-spacemesh/blob/develop/config/logging.go#L48 but I'm not sure what will be the impact.

2024-11-13 09:48 UTC, poszu requested changes

2024-11-13 09:48 UTC, poszu commented on api/grpcserver/v2alpha1/transaction.go
> +		zap.String("tx_id", raw.ID.String()),
```suggestion
		zap.Stringer("tx_id", raw.ID),
```

2024-11-13 09:49 UTC, poszu approved these changes

2024-11-13 09:53 UTC, poszu commented
> We can configure specific logger for grpc service as stated in [`develop`/config/logging.go#L48](https://github.com/spacemeshos/go-spacemesh/blob/develop/config/logging.go?rgh-link-date=2024-11-12T15%3A48%3A33Z#L48) but I'm not sure what will be the impact.

It is already using a logger configured with `GrpcLoggerLevel`. It is configured via middleware here: https://github.com/spacemeshos/go-spacemesh/blob/f711c614a47c7cabcfa886cea263df01dfb98110/api/grpcserver/grpc.go#L138

2024-11-13 10:28 UTC, kacpersaw commented
bors merge

2024-11-13 11:13 UTC, closed without merging