v2alpha1: Implement v2alpha1 ActivationService.Highest rpc
spacemeshos/go-spacemesh pull request #6552
Opened 2024-12-18 15:20 UTC by kacpersaw

## Description
Closes #6539

This pull request introduces several significant changes to the `api/grpcserver/v2alpha1/activation.go` file, including the addition of a new interface, modifications to the `ActivationService` struct, and the implementation of new methods. Additionally, it includes updates to the testing framework and dependencies. Below is a summary of the most important changes.

### Changes to `activation.go`:

* Added a new `activationProvider` interface with methods `GetAtx` and `MaxHeightAtx`.
* Modified the `NewActivationService` function to accept additional parameters `atxProvider` and `goldenAtx`.
* Added a new method `Highest` to the `ActivationService` struct to return the highest ATX.

### Mock and Test Updates:

* Generated a mock for the `activationProvider` interface in `activation_mocks.go`.
* Updated tests in `activation_test.go` to use the new `activationProvider` mock and added a new test for the `Highest` method. [[1]](diffhunk://#diff-da2bd880d3c3e3214a6eb2737b9f4c53ad1a803ea6cd93f6735d97d29d2ba04eR29-R30) [[2]](diffhunk://#diff-da2bd880d3c3e3214a6eb2737b9f4c53ad1a803ea6cd93f6735d97d29d2ba04eL36-R41) [[3]](diffhunk://#diff-da2bd880d3c3e3214a6eb2737b9f4c53ad1a803ea6cd93f6735d97d29d2ba04eR235-R237) [[4]](diffhunk://#diff-da2bd880d3c3e3214a6eb2737b9f4c53ad1a803ea6cd93f6735d97d29d2ba04eL247-R256) [[5]](diffhunk://#diff-da2bd880d3c3e3214a6eb2737b9f4c53ad1a803ea6cd93f6735d97d29d2ba04eR287-R339)

2024-12-18 15:26 UTC, fasmat requested changes

2024-12-18 15:26 UTC, fasmat commented on node/node.go
> +		service := v2alpha1.NewActivationService(app.apiDB, app.cachedDB, types.ATXID(app.Config.Genesis.GoldenATX()))
I thought `app.cachedDB` should not be used in the API any more? The method `MaxHeightAtx` is just `atxs.GetIDWithMaxHeight(db, types.EmptyNodeID, atxs.FilterAll)` and `GetAtx` is also just `atxs.Get(db, id)`.

2024-12-18 15:26 UTC, fasmat commented on api/grpcserver/v2alpha1/activation.go
> +}
This should not be necessary.

2024-12-18 16:13 UTC, fasmat approved these changes

2024-12-18 16:37 UTC, kacpersaw commented
bors merge

2024-12-19 08:53 UTC, fasmat commented
bors merge

2024-12-19 09:41 UTC, closed without merging