#553
spacemeshos/go-spacemesh pull request #797
Opened 2019-04-08 12:06 UTC by almogdepaz

2019-04-08 14:29 UTC, barakshani commented on tortoise/ninja_tortoise.go
> +			if _, found := ni.tExplicit[b.ID()][x.Layer()]; found { //if Texplicit[b][x]!=0 check correctness of x.layer and found
in the code comment, x should be layer(x)

2019-04-16 14:53 UTC, zalmen requested changes

2019-04-16 14:53 UTC, zalmen commented on mesh/meshdb.go
>  			//todo: add err returned from handler, if error is returned return it, if not - keep going
remove todo

2019-04-16 14:53 UTC, zalmen commented on tortoise/ninja_tortoise.go
> +			for _, i := range ni.patterns[i] {
you are using `i` twice, replace one of them

2019-04-16 14:53 UTC, zalmen commented on tortoise/ninja_tortoise.go
> +	wg.Add(1)
should be inside the for loop

2019-04-16 14:53 UTC, zalmen commented on tortoise/ninja_tortoise.go
>  	}
Comment regarding old code below - in the `ni.Error` few lines below, you should also print the error

2019-04-17 10:13 UTC, zalmen approved these changes

2019-04-17 10:28 UTC, merged