P2p gossip propagate once
spacemeshos/go-spacemesh pull request #809
Opened 2019-04-12 10:00 UTC by y0sher

2019-04-14 10:35 UTC, y0sher commented on p2p/gossip/protocol.go
> +		//invalidMessageQ: make(map[hash]bool),     // todo : remember to drain this
to remove

2019-04-14 10:36 UTC, y0sher commented on p2p/gossip/protocol.go
> +	return
not needed

2019-04-15 07:30 UTC, zalmen requested changes

2019-04-15 07:30 UTC, zalmen commented on p2p/gossip/protocol.go
> +		p.Log.Info("Gossip protocol failed to send msg (calcHash %d) to peer %v, first attempt. err=%v", checksum, p.pubkey, err)
This should be an Error, not info.

2019-04-15 07:30 UTC, zalmen commented on p2p/gossip/protocol.go
> +		p.Log.Info("Gossip protocol failed to send msg (calcHash %d) to peer %v, first attempt. err=%v", checksum, p.pubkey, err)
(I know it's my code :))

2019-04-15 07:30 UTC, zalmen commented on p2p/gossip/protocol.go
> +			p.Log.Info("Gossip protocol failed to send msg (calcHash %d) to peer %v, second attempt. err=%v", checksum, p.pubkey, err)
also should be an error

2019-04-15 07:30 UTC, zalmen commented on p2p/gossip/protocol.go
> +		for e := range exclude {
In which case do you expect seeing more than one sender?

2019-04-15 07:30 UTC, zalmen commented on p2p/gossip/protocol.go
> +		for e := range exclude {
Currently, the only call to this method passes one sender

2019-04-15 07:30 UTC, zalmen commented on p2p/gossip/protocol.go
> +	prot.processMessage(prot.localNodePubkey, msg) // todo: pass sender
Why the "todo"?

2019-04-15 07:30 UTC, zalmen commented on p2p/gossip/protocol.go
> +		// todo : - maybe block this peer since he sends us old messages
add log print

2019-04-15 15:49 UTC, zalmen approved these changes

2019-04-15 15:54 UTC, merged