Fixed error handling
spacemeshos/go-spacemesh pull request #840
Opened 2019-04-21 13:14 UTC by gavraz

2019-04-21 18:02 UTC, zalmen requested changes

2019-04-21 18:02 UTC, zalmen commented on activation/atxdb.go
> +	if len(ids) == 0 { // GetIdentity succeeded but no ATXs, this is a fatal error
add more context to the error - "no active IDs for known node".

2019-04-21 18:02 UTC, zalmen commented on hare/algorithm.go
> +// TODO: move to unit test
move it as part of this PR (bet you whatever you want that you knew that I'll write this comment ;)

2019-04-22 07:17 UTC, gavraz commented on activation/atxdb.go
> +	if len(ids) == 0 { // GetIdentity succeeded but no ATXs, this is a fatal error
Fixed

2019-04-22 07:18 UTC, gavraz commented on hare/algorithm.go
> +// TODO: move to unit test
You can't use anything from unit test files (it is not part of the compiled executable)

2019-04-22 07:23 UTC, zalmen approved these changes

2019-04-22 08:12 UTC, merged